fix(licenses): add bubble for licences and add ODBL Licences
GrottoCenter/grottocenter-front pull request #16
Opened 2021-09-30 16:37 UTC by BastienBoymond

2021-09-30 17:52 UTC, bsoufflet commented
@maximenathan : Peux tu rapidement jeter un oeil à cette premiere PR de @BastienBoymond ? Merci :)

2021-09-30 17:59 UTC, bsoufflet requested changes
Peux tu renommer le fichier image en minuscule ? odbl.png

2021-09-30 18:01 UTC, bsoufflet commented
@urien : Ne faudrait il pas écrire ce texte : 
This {DATA(BASE)-NAME} is made available under the Open Database License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in individual contents of the database are licensed under the Database Contents License: http://opendatacommons.org/licenses/dbcl/1.0/
source : https://opendatacommons.org/licenses/odbl/

2021-09-30 18:02 UTC, bsoufflet commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/ODBL.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
@BastienBoymond : La traduction du title fonctionne toute seul ici ?

2021-09-30 18:13 UTC, BastienBoymond commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/ODBL.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
Je ne l'ai pas tester et en venant de le tester ça ne marche 
À tu une idée de comment je peux traduire dans un tittle car en regardant le code c'est souvant que avec des
<translate> mais ça ne marche pas dans un tittle=""

2021-09-30 18:19 UTC, bsoufflet commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/ODBL.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
@BastienBoymond : @maximenathan pourra certainement mieux répondre que moi...

Quelque chose comme ca ne fonctionnerait pas ? 
```
title={<Translate>disabled</Translate>}>
```
(visible dans DisabledTooltip)

2021-09-30 18:43 UTC, urien commented
> 
> 
> @urien : Ne faudrait il pas écrire ce texte : This {DATA(BASE)-NAME} is made available under the Open Database License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in individual contents of the database are licensed under the Database Contents License: http://opendatacommons.org/licenses/dbcl/1.0/ source : https://opendatacommons.org/licenses/odbl/

Effectivement c'est plus conforme a la licence

2021-09-30 19:19 UTC, BastienBoymond commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/ODBL.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
j'ai esseyer et ça m'ecris [Object Object]

2021-10-04 09:48 UTC, Clm-Roig commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/ODBL.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
```js 
<Translate>texte</Translate>
``` 
retourne un nœud HTML ou quelque chose du genre.
Pour obtenir une String, il faut utiliser :
```js
formatMessage({ id: 'text' })
```

2021-10-04 09:52 UTC, Clm-Roig requested changes

2021-10-04 09:52 UTC, Clm-Roig commented on packages/web-app/src/conf/Config.jsx
> +
Il me semble que l'intérêt du symbole `*` c'est justement de ne pas avoir à mentionner toutes les langues si l'url est la même pour toutes les langues ^^

2021-10-06 07:25 UTC, maximenathan commented
@BastienBoymond bravo pour la première PR :clap: 
Pour les descriptions, peux tu un peu détailler / link vers l'issue et avoir un petit apercus **Avant** / **Après** ?

2021-10-06 20:06 UTC, BastienBoymond commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/ODBL.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
J'ai beau essayer soit  je ne compile pas. Soit il y a écrit [Objet Objet]

2021-10-06 20:12 UTC, BastienBoymond commented
Voici un avant Apres
Le seul truc qui me manque actuellement c'est les traduction quand on met la souris sur les 2 images de licences.
Je ne trouve pas du tout comment faire
![avant](https://user-images.githubusercontent.com/71839723/136276205-b6c3e93e-4278-4fab-9c60-e7e05f501da0.PNG)
![Apres](https://user-images.githubusercontent.com/71839723/136276211-1dee8719-6f1a-49dd-bc1c-7c0573f26e14.PNG)

2021-10-06 23:18 UTC, bsoufflet commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/ODBL.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
@maximenathan ?

2021-10-09 09:25 UTC, urien commented
Je propose qu'on ne mette que le texte en Anglais.
Je vais modifier les mentions légales pour rajouter un chapitre sur les licences appliquées

2021-10-09 09:43 UTC, urien commented
Voila lers mentions légales en Français avec une indication sur les licences. J'ai sollicité l'avis du Conseil d'Administration de Wikicaves
https://wiki.grottocenter.org/wiki/Template:Fr/Legal_and_Privacy_Statement#Mentions_l%C3%A9gales

2021-10-09 09:45 UTC, urien commented
Clément a fait une mise à jour des traductions.
Bastien on gère la localisation avec Transifex. Souhaites tu que je te donne un accès ?

2021-10-10 13:46 UTC, BastienBoymond commented
Je ne connais pas Transiflex il sert juste a avoir la localisation d'un utilisateur ?

2021-10-10 14:08 UTC, urien commented
> 
> 
> Je ne connais pas Transiflex il sert juste a avoir la localisation d'un utilisateur ?

On lui donne le fichier json pour l'anglais et il permet aux traducteurs de produire les json dans les autres langues. Il y a (avait) un script pour récupérer automatiquement les json à jour sur transifex. Je peux te donner des droits pour poster sur transfex le fichier json de l'anglais si tu le modifie
Clément afait des modifs après toi, tu pourras récupérer les fichiers qu'il a posté sur transifex

2021-11-22 22:46 UTC, bsoufflet approved these changes

2021-11-22 22:46 UTC, bsoufflet commented
@Clm-Roig On valide cette PR ? Pas très grave ssi c'est que en anglais pour l'instant non ?

2021-11-22 23:01 UTC, bsoufflet commented
@BastienBoymond : il y aura un petit conflit à résoudre avant de merge si @Clm-Roig est ok pour merge ;)

2021-11-29 16:33 UTC, Clm-Roig requested changes

2021-11-29 16:33 UTC, Clm-Roig commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/odbl.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
Pour traduire le title, il faut utiliser formatMessage() du hook useIntl(). Tu veux que je m'en charge ? :slightly_smiling_face: @BastienBoymond

2021-11-29 17:17 UTC, BastienBoymond commented on packages/web-app/src/components/common/SideMenu/Footer.jsx
> +            <LicenceImage src="/images/odbl.png" alt="ODBL license" title="The ODBL license applies to all data that is not copyrighted"/>
je veux bien comme ça je pourrais voir a quoi ça ressemble

2021-12-01 10:01 UTC, Clm-Roig commented
@BastienBoymond je viens de commit ce qu'il manquait à cette PR :slightly_smiling_face: N'hésite pas à me demander si quelque chose n'est pas clair.

Je merge une fois que j'ai ton approbation (et celles des autres développeurs).

2021-12-01 11:00 UTC, urien commented
Sur mon téléphone cela fonctionne bien.

Le mer. 1 déc. 2021 à 11:11, github-actions[bot] ***@***.***>
a écrit :

> Azure Static Web Apps: Your stage site is ready! Visit it here:
> https://orange-rock-0d4f87503-16.westeurope.azurestaticapps.net
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrottoCenter/grottocenter-front/pull/16#issuecomment-983487760>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI4OWDOAVB3B7O2AL3Z4U3UOXYGRANCNFSM5FCYAT2Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-01 11:05 UTC, BastienBoymond commented
d'accord j'ai compris ce qui a été fais et je comprend un peux mieux du coup

2021-12-01 14:55 UTC, Clm-Roig approved these changes

2021-12-01 14:58 UTC, Clm-Roig commented
> d'accord j'ai compris ce qui a été fais et je comprend un peux mieux du coup

Super ! Concernant les traductions françaises, j'ai préféré les supprimer pour qu'on les gère dans Transifex. J'ai peur que ça génère des conflits ou que la synchro se passe mal si on ajoute des traductions dans fr.json plutôt que sur Transifex. 

Par contre l'ajout dans en.json est obligatoire et Transifex se synchronise dessus pour proposer les mots / phrases à traduire aux traducteurs 🙂

2021-12-01 16:18 UTC, merged