feat(import): add import csv module
GrottoCenter/grottocenter-front pull request #21
Opened 2021-10-18 20:17 UTC by AxelCanton

2021-10-26 12:53 UTC, Clm-Roig requested changes

2021-10-26 12:53 UTC, Clm-Roig commented on packages/web-app/src/components/appli/ImportCSV/ImportContainer.jsx
> +  }, [validatedSteps, currentFormStep, formSteps]);
Pour éviter de désactiver eslint, est-ce que le code suivant ne suffirait pas ? 

```jsx
useEffect(() => {
    if (
      currentFormStep === formSteps.length ||
      !includes(currentFormStep, validatedSteps)
    ) {
      enableNextStep();
    } else {
      disableNextStep();
    }
  }, [
    validatedSteps,
    currentFormStep,
    formSteps,
    enableNextStep,
    disableNextStep
  ]);
```

2021-10-26 12:53 UTC, Clm-Roig commented on packages/web-app/src/components/appli/ImportCSV/ImportContainer.jsx
> +            )}
```jsx
let title = '';
  switch(selectedType) {
    case ENTRANCE:
      title = 'Entrances import';
      break;
    case DOCUMENT:
      title = 'Documents import';
      break;
    default:
      break;
  }

  return (
    <>
      <ImportTabs />
      <Card className={classes.root}>
        <CardContent>
          <Typography color="secondary" variant="h1">
            <Translate>{title}</Translate>    
          </Typography>
```

Sans oublier l'import de "DOCUMENT" en haut du fichier.

Je trouve ça plus clair et plus facilement maintenable : quand on aura un autre type de données, il suffira de rajouter un case.

2021-10-26 12:53 UTC, Clm-Roig commented on packages/web-app/src/components/appli/ImportCSV/ImportKarstlinkInfo.jsx
> +              id: selectType === 0 ? 'Example - Entrance' : 'Example - Document'
Utiliser la constante **DOCUMENT** ou **ENTRANCE** au lieu de 0

2021-10-26 12:53 UTC, Clm-Roig commented on packages/web-app/src/components/appli/ImportCSV/ImportSteps/Step2.jsx
> +  }, []);
```jsx

useEffect(() => {
...
}, [updateAttribute]);
```

ne suffit pas pour contenter eslint ?

2021-10-26 12:53 UTC, Clm-Roig commented on packages/web-app/src/components/appli/ImportCSV/ImportSteps/Step3.jsx
> +} from '@material-ui/core';
ça aurait été top d'utiliser le composant qu'on a dans **common/Table**, il fait beaucoup de chose pour toi de base :slightly_smiling_face:

2021-10-26 12:53 UTC, Clm-Roig commented on packages/web-app/src/components/appli/ImportCSV/ImportSteps/Step4.jsx
> +  }, []);
```jsx
useEffect(() => {
    dispatch(checkRowsInBdd(selectedType, importData));
    return () => {
      dispatch(resetImportState());
    };
  }, [dispatch, selectedType, importData]);
```

pour contenter eslint ?

2021-10-26 12:53 UTC, Clm-Roig commented on packages/web-app/src/reducers/ImportCsvReducer.js
> +      };
Tu peux regrouper certains case qui font la même chose. Exemple : 
```jsx
case CHECK_ROWS_START:
      return {
        ...state,
        isLoading: true
      };

case IMPORT_ROWS_START:
      return {
        ...state,
        isLoading: true
      };
```

devient : 

```jsx
case CHECK_ROWS_START:
case IMPORT_ROWS_START:
      return {
        ...state,
        isLoading: true
      };
```

2021-10-26 13:03 UTC, Clm-Roig commented
L'exemple actuel que l'on peut télécharger sur la première page (V4.csv)  plante quand on essaie de l'utiliser. L'erreur est la suivante : 

`2,"Error: This iso code is incorrect : FR "`

J'approfondis les tests pour voir ce qui cloche puis j'éditerai ce message.

**EDIT :** j'ai trouvé l'erreur ! Dans la colonne **karstlink:hasAccessDocument/dc:language** du csv il est entré la valeur "FR " (avec un espace après FR) au lieu de "FR" (sans espace) !

2021-10-29 10:37 UTC, AxelCanton commented on packages/web-app/src/reducers/ImportCsvReducer.js
> +      };
Je savais pas qu'on pouvait faire comme ça !

2021-10-29 10:50 UTC, Clm-Roig commented on packages/web-app/src/reducers/ImportCsvReducer.js
> +      };
La magie du Switch ! Et tant que tu retournes rien dans ton case ou que tu n'utilises pas 'break', plusieurs cases peuvent avoir lieu. C'est super flexible.

2021-10-31 10:05 UTC, urien commented
J'ai mis à jour le fichier V4.csv sans l'espace après FR

2021-11-08 12:54 UTC, Clm-Roig commented
@AxelCanton du nouveau de ce côté-là ?

2021-11-11 18:13 UTC, AxelCanton commented
J'étais en période d'exam !
Là j'ai fait pas mal de modification, déjà j'ai pris tous tes retours en compte, mais j'ai aussi amélioré le visuel de la dernière étape. J'utilise des Alert pour les messages (de type "va être importé..."), et j'ai aussi améliorer les traductions pour prendre en compte le pluriel/singulier.

2021-11-11 20:26 UTC, urien commented
Salut Axel, merci de t'occuper de ces développements
Il y a un problème. L'import csv doit être accessible aux modérateurs seulement. Là il est accessible à toutes les personnes qui se connectent (les utilisateurs)

2021-11-11 20:59 UTC, AxelCanton commented
Pourtant un utilisateur lambda peut créer une cavité ou un document, pourquoi limiter l'import à des modérateurs seulement ?

2021-11-11 21:06 UTC, urien commented
Il me semble qu'il y a un réglage possible au niveau des route et des
autorisations.

Frédéric

Le jeu. 11 nov. 2021 à 21:59, AxelCanton ***@***.***> a
écrit :

> Pourtant un utilisateur lambda peut créer une cavité ou un document,
> pourquoi limiter l'import à des modérateurs seulement ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrottoCenter/grottocenter-front/pull/21#issuecomment-966621153>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI4OWBBHY5LK6THVZLUARLULQVEHANCNFSM5GHPPZBA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-11 21:11 UTC, AxelCanton commented
Oui oui c'est possible et pas très dur, je trouvais ça bizarre sur le concept seulement. D'ailleurs au niveau de l'API je vérifie que l'utilisateur qui importe possède le droit de créer des documents pour l'import de document ou le droit de créer des cavités pour les cavités.
Il faudra que je rajoute un droit spécial import et je l'affecte aux modérateurs. Est-ce que tu penses qu'il y a besoin d'un seul droit pour tout type d'import ou je crée un droit par type (document et entrance à l'heure actuelle). Si à l'avenir on souhaite limiter l'import des documents aux modérateurs et autoriser n'importe quel utilisateurs à importer des cavités il faudrait un droit par type.

2021-11-11 22:49 UTC, Clm-Roig commented
Je verrais bien un en droit "Mass import" qu'on pourra donc affecter à chaque entité (ex : "Document - Mass import", "Entrance - Mass import")

2021-11-12 05:42 UTC, urien commented
La proposition de Clément me convient.
L'import via csv impacte la base de manière importante, cela permettra de
maîtriser qui a accès à cette possibilité

Le jeu. 11 nov. 2021 à 23:49, Clément Roig ***@***.***> a
écrit :

> Je verrais bien un en droit "Mass import" qu'on pourra donc affecter à
> chaque entité (ex : "Document - Mass import", "Entrance - Mass import")
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrottoCenter/grottocenter-front/pull/21#issuecomment-966680397>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI4OWHUIUVRRGAFL6ZE24TULRB7VANCNFSM5GHPPZBA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-13 14:54 UTC, Clm-Roig commented
J'ai amélioré l'UI pour les erreurs de CSV quand on checke les données : 
![image](https://user-images.githubusercontent.com/20704943/141648221-bdb522f9-dbaf-4589-b2b9-7a5d32e95992.png)

Le code à mettre dans le fichier Step2.jsx (sinon je commit dans ta PR, comme tu veux @AxelCanton) est ci-dessous.

<details>
<summary>Step2.jsx</summary>

```jsx
import React, { useContext, useEffect, useState } from 'react';
import { CSVReader } from 'react-papaparse';
import { useTheme } from '@material-ui/core/styles';
import { Alert } from '@material-ui/lab';
import { useIntl } from 'react-intl';
import { ImportPageContentContext } from '../Provider';
import checkData from '../checkData';

const inputRef = React.createRef();

const Step2 = () => {
  const { updateAttribute, selectedType } = useContext(
    ImportPageContentContext
  );
  const theme = useTheme();
  const { formatMessage } = useIntl();

  const [errorsRow, setErrorsRow] = useState([]);

  const handleOnFileLoad = data => {
    const errors = checkData(data, selectedType, formatMessage);
    if (errors.length === 0) {
      updateAttribute('importData', data);
      updateAttribute('fileImported', true);
    } else {
      setErrorsRow(errors);
    }
  };

  const handleOnRemoveFile = () => {
    setErrorsRow([]);
    updateAttribute('fileImported', false);
  };

  const transformHeader = header => {
    return header.trim();
  };

  // react-papaparse reset its content if go back to that step, so do we.
  useEffect(() => {
    updateAttribute('importData', undefined);
    updateAttribute('fileImported', false);
  }, [updateAttribute]);

  return (
    <>
      <CSVReader
        ref={inputRef}
        onFileLoad={handleOnFileLoad}
        onRemoveFile={handleOnRemoveFile}
        addRemoveButton
        isReset={false}
        progressBarColor={theme.palette.primary1Color}
        config={{
          transformHeader,
          header: true,
          skipEmptyLines: true
        }}>
        <span>
          {formatMessage({ id: 'Drop CSV file here or click to upload.' })}
        </span>
      </CSVReader>
      {errorsRow.map(err => (
        <Alert
          severity="error"
          key={err}>{`Row ${err.row} : ${err.errorMessage}`}</Alert>
      ))}
    </>
  );
};

Step2.propTypes = {};

export default Step2;
```
</details>

2021-11-13 15:07 UTC, Clm-Roig commented
Dans `DownloadButton`, j'ai ajouté `size="small"` au `IconButton` pour éviter qu'il n'agrandisse l'Alert.

<details>
<summary>Le code de DownloadButton.jsx en cliquant ici ! </summary>

```jsx
import React from 'react';
import { CSVDownloader } from 'react-papaparse';
import PropTypes from 'prop-types';
import CloudDownloadIcon from '@material-ui/icons/CloudDownload';
import { IconButton, Tooltip } from '@material-ui/core';
import { useIntl } from 'react-intl';

const DownloadButton = ({ data, filename }) => {
  const { formatMessage } = useIntl();
  return (
    <>
      <CSVDownloader
        data={data}
        type="button"
        filename={filename}
        style={{
          'background-color': 'transparent',
          'background-repeat': 'no-repeat',
          border: 'none',
          cursor: 'pointer',
          overflow: 'hidden',
          outline: 'none'
        }}>
        <Tooltip title={formatMessage({ id: 'Download information' })}>
          <IconButton color="primary" size="small">
            <CloudDownloadIcon />
          </IconButton>
        </Tooltip>
      </CSVDownloader>
    </>
  );
};

DownloadButton.propTypes = {
  data: PropTypes.arrayOf(PropTypes.objectOf(PropTypes.string)).isRequired,
  filename: PropTypes.string.isRequired
};

export default DownloadButton;
```

</details>

2021-11-13 15:10 UTC, Clm-Roig commented
Sinon c'est tout bon pour moi ! Tu me dis @AxelCanton si tu veux que je commit les changements que je te demande et merge ta PR ou si tu t'en occupes :slightly_smiling_face:

2021-11-13 17:58 UTC, urien commented
L'import csv apparaît toujours dans la boîte à outil des utilisateurs

Le sam. 13 nov. 2021 à 18:52, github-actions[bot] ***@***.***>
a écrit :

> Azure Static Web Apps: Your stage site is ready! Visit it here:
> https://orange-rock-0d4f87503-21.westeurope.azurestaticapps.net
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrottoCenter/grottocenter-front/pull/21#issuecomment-968108195>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI4OWGZWU323SEAH2JBD33UL2QXXANCNFSM5GHPPZBA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-14 06:36 UTC, urien commented
Je viens d'essayer d'importer un csv. J'ai une notification d'erreur sans explication
![image](https://user-images.githubusercontent.com/1165144/141670217-056131b6-bf3c-4522-aad3-89e43435ebab.png)
En fait je mettais un csv de document dans le module d'import de cavité

Ensuite l'import a échoué mais l'explication était claire. Le type de document  http://id.loc.gov/vocabulary/marcgt/boo  n'est pas reconnu. Je crois que les différents types sont dans une table, il faudra sans doute faire le point sur ce qu'elle contient

2021-11-14 06:40 UTC, urien commented
Lorsque je mets http://purl.org/dc/dcmitype/Text pour le type j'ai en retour
AdapterError: Unexpected error from database adapter: value too long for type character(5)

2021-11-14 06:52 UTC, urien commented
Test avec une entrée
De la même manière j'ai une erreur mais pas de texte associé
![screenshot-orange-rock-0d4f87503-21 westeurope azurestaticapps net-2021 11 14-07_43_49](https://user-images.githubusercontent.com/1165144/141670596-4ee1e8bc-1824-4b68-8328-8c0f6217a1ee.png)
Ensuite l'import se déroule bien https://orange-rock-0d4f87503-21.westeurope.azurestaticapps.net/ui/entries/75209
C'est super !

2021-11-15 09:22 UTC, Clm-Roig commented
C'est ma faute les erreurs "vides", je corrige ça de suite

2021-11-15 09:41 UTC, Clm-Roig commented
Je me mets à tester pour les documents et je te fais un retour quant à tes soucis @urien

2021-11-15 12:28 UTC, AxelCanton commented
Du coup tous les retours ont été pris en compte, il reste plus qu'à adapter le back et on merge ?

2021-11-15 12:43 UTC, urien commented
Au niveau menu c'est ok.
Il y a un pb au niveau front. Si je veux importer un csv de documents et que je mets un fichier csv correspondant à des entrées cela fonctionne
![screenshot-orange-rock-0d4f87503-21 westeurope azurestaticapps net-2021 11 15-13_35_36](https://user-images.githubusercontent.com/1165144/141783305-2c960879-95c0-439c-b13b-b34200db9f0e.png)

Mais si je mets un csv correspondant à des documents il le prend bien aussi
A mon avis on peut laisser ainsi car c'est un module qui s'adresse à des modérateurs qui doivent bien maitriser leur sujet
Les messages apparaissent bien

2021-11-15 12:49 UTC, Clm-Roig commented
> http://purl.org/dc/dcmitype/Text

Problème côté back avec les sujets apparemment, je m'en occupe sur l'autre repo.

2021-11-15 12:49 UTC, Clm-Roig commented
> Lorsque je mets http://purl.org/dc/dcmitype/Text pour le type j'ai en retour AdapterError: Unexpected error from database adapter: value too long for type character(5)

Problème côté back (indépendant du type je pense) avec les sujets apparemment, je m'en occupe sur l'autre repo.

2021-11-15 13:00 UTC, AxelCanton commented
On est d'accord que la colonne rdf:type correspond au type du fichier csv (entrance ou document) ? @urien

2021-11-15 13:28 UTC, urien commented
Non, cela n'existe que dans le csv des documents. Cela correspond au type
de document : collection, issue, article, image,...

Le lun. 15 nov. 2021 à 14:01, AxelCanton ***@***.***> a
écrit :

> On est d'accord que la colonne rdf:type correspond au type du fichier csv
> (entrance ou document) ? @urien <https://github.com/urien>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrottoCenter/grottocenter-front/pull/21#issuecomment-968886871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI4OWBMCNWFUPKK4AWTN23UMEAA7ANCNFSM5GHPPZBA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-15 13:29 UTC, urien commented
Oups, oui tu as raison Axel.

Le lun. 15 nov. 2021 à 14:28, Frédéric Urien ***@***.***> a
écrit :

> Non, cela n'existe que dans le csv des documents. Cela correspond au type
> de document : collection, issue, article, image,...
>
> Le lun. 15 nov. 2021 à 14:01, AxelCanton ***@***.***> a
> écrit :
>
>> On est d'accord que la colonne rdf:type correspond au type du fichier csv
>> (entrance ou document) ? @urien <https://github.com/urien>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/GrottoCenter/grottocenter-front/pull/21#issuecomment-968886871>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAI4OWBMCNWFUPKK4AWTN23UMEAA7ANCNFSM5GHPPZBA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-11-15 13:32 UTC, urien commented
L'erreur que je décris viens de la valeur mise dans karstlink:documentType

Le lun. 15 nov. 2021 à 14:28, Frédéric Urien ***@***.***> a
écrit :

> Oups, oui tu as raison Axel.
>
> Le lun. 15 nov. 2021 à 14:28, Frédéric Urien ***@***.***> a
> écrit :
>
>> Non, cela n'existe que dans le csv des documents. Cela correspond au type
>> de document : collection, issue, article, image,...
>>
>> Le lun. 15 nov. 2021 à 14:01, AxelCanton ***@***.***> a
>> écrit :
>>
>>> On est d'accord que la colonne rdf:type correspond au type du fichier
>>> csv (entrance ou document) ? @urien <https://github.com/urien>
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/GrottoCenter/grottocenter-front/pull/21#issuecomment-968886871>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AAI4OWBMCNWFUPKK4AWTN23UMEAA7ANCNFSM5GHPPZBA>
>>> .
>>> Triage notifications on the go with GitHub Mobile for iOS
>>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>>> or Android
>>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>>
>>>
>>

2021-11-15 14:23 UTC, urien commented
Désormais j'ai une erreur "Row 2 : The type column is incorrect."
Quand je mets le fichier joint
Auparavant ce fichier passait et cela faisait une erreur a l'étape 4
[Prospection.csv](https://github.com/GrottoCenter/grottocenter-front/files/7539279/Prospection.csv)

2021-11-15 15:18 UTC, urien commented
c'est bon j'ai importé mon fichier
https://orange-rock-0d4f87503-21.westeurope.azurestaticapps.net/ui/documents/130200
Cela fonctionne avec le code pour la classification BBS (ici 2.11) alors
que dans l'exemple c'est une url. Mais c'est parfait ainsi

Le lun. 15 nov. 2021 à 15:57, github-actions[bot] ***@***.***>
a écrit :

> Azure Static Web Apps: Your stage site is ready! Visit it here:
> https://orange-rock-0d4f87503-21.westeurope.azurestaticapps.net
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrottoCenter/grottocenter-front/pull/21#issuecomment-968991953>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI4OWAWFY5XXYJI3IJOHILUMENUJANCNFSM5GHPPZBA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-15 15:30 UTC, Clm-Roig approved these changes

2021-11-15 15:30 UTC, merged