[ENTRANCE PAGE] Display various information
GrottoCenter/grottocenter-front pull request #298
Opened 2021-12-14 08:38 UTC by Clm-Roig

Fix #27

Also, I updated the entrance link: it's now /ui/entrances/1234 (instead of /ui/entries/1234).

2021-12-14 08:50 UTC, Clm-Roig commented
Exemple complet ici (j'ai vérifié en BD, tous les champs doivent être visibles normalement) : https://orange-rock-0d4f87503-298.westeurope.azurestaticapps.net/ui/entrances/14

Je viens de me rendre compte que je n'avais pas géré la température, je m'en occupe de suite.

2021-12-14 10:25 UTC, urien approved these changes
C'est chouette. 
Il y a un truc sur les auteurs mais je crois que tu as fait un ticket.

2021-12-14 10:30 UTC, Clm-Roig commented
J'ai corrigé l'affichage de l'auteur dans la prochaine PR qui concerne l'accès => #300

2021-12-14 10:39 UTC, urien commented
Il y a 3 instances qui tournent : cela empêche  #300 de se déployer. Il faut merger pour clore une instance ?

2021-12-14 11:16 UTC, Clm-Roig commented
> Il y a 3 instances qui tournent : cela empêche #300 de se déployer. Il faut merger pour clore une instance ?

Oui c'est ça ! Mais j'aimerais une validation du code par Benjamin ou Maxime avant de merger.

2021-12-14 11:28 UTC, Clm-Roig commented
Le problème des 3 instances est corrigé, les 2 PRs sont désormais visualisables.

2021-12-14 23:59 UTC, bsoufflet commented
Voici d'abord des commentaires d'UI UX (qui sont à prendre si facile ou à laisser sinon ;) ) : 
- Pour faciliter le copier / coller des coordonnées GPS je changerais bien le format de `Latitude: 45.0766 - Longitude: 5.3951` vers `Lat / Lng: 45.0766 5.3951`
- `Choranche, Isère (38), Auvergne-Rhône-Alpes (ARA), FR` -> je réduirais la police d'un cran
- Pour l'organisation des 6 dernières informations (developpement, profondeur, date de decouverte, ...) je réorganiserais bien en 2 lignes de 3 éléments. Par contre il me semble important d'éviter de ne mettre que des icones car souvent une icone ne parle pas d'elle meme... Il est donc préférable de mettre (le plus souvent) un label. Une organisation l'exemple ci dessous me semble pas mal avec l'icone à gauche, le label en haut à droite grisé et petit et la valeur en bas à droite en un peu plus gros (et pas grisé) : 
![signal-2021-12-15-005109](https://user-images.githubusercontent.com/985903/146097589-80acd387-80f9-4ff8-802c-d7bf62f7ace2.jpeg)
- Concernant les notations en bas, plusieurs membres pensent qu'il n'est pas judicieux de mettre ces informations trop en avant car elles accentuent le coté sportif (à l'opposé de scientifique) de grottocenter. Du coup je passerais bien le font-size des étoiles de 2.4 rem à 1.4 rem.

2021-12-15 00:08 UTC, bsoufflet requested changes

2021-12-15 00:08 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/Properties.jsx
> +          value={`${temperature} °C`}
N'y aurait il pas un problème avec la gestion des valeurs vides ?
![image](https://user-images.githubusercontent.com/985903/146098665-52f3b19f-081c-4975-ab2d-77035b68ef47.png)
https://orange-rock-0d4f87503-298.westeurope.azurestaticapps.net/ui/entrances/21102

2021-12-15 14:13 UTC, Clm-Roig commented
Je suis arrivé à ça niveau interface, je pushe dans un instant : 
![image](https://user-images.githubusercontent.com/20704943/146202087-41fd66e8-94e6-4834-b08d-39769fdc5955.png)

Pour le label gris en petit, la solution qu'il y avait avant c'était un tooltip au survol de la valeur. Je préfère avec ce label, c'est plus accessible et explicite.

2021-12-15 14:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Properties.jsx
> +  transform: scale(0.85);
J'ai pas trouvé mieux comme solution pour diminuer la taille des notes. Avant c'était en "small" et "x-small" n'existe pas sur ce composant.

2021-12-15 14:49 UTC, urien commented
Cela me plait beaucoup !

2021-12-15 15:03 UTC, Clm-Roig commented
Petite cerise sur le gâteau : j'ai ajouté un lien vers le massif dans lequel se situe l'entrée :slightly_smiling_face:

2021-12-15 15:11 UTC, urien commented
Merci, 
Ce sont ces liens entre les ressources qui vont faire la richesse de l'application

2021-12-15 18:04 UTC, bsoufflet approved these changes

2021-12-15 18:10 UTC, bsoufflet commented
C'est bien mieux ! Merci @Clm-Roig 
Il y a juste :
- "Présence d'un siphon" que j'écrirais plus petit...
- je mettrais cote à cote profondeur et développement
- Le nom de l'entry est parfois très long et ca rend pas génial dans ce cas car la police du nom est grosse (mais je n'ai pas de solution en tete...) -> https://orange-rock-0d4f87503-298.westeurope.azurestaticapps.net/ui/entrances/24610

2021-12-15 18:44 UTC, Clm-Roig commented
> C'est bien mieux ! Merci @Clm-Roig Il y a juste :
> 
>     * "Présence d'un siphon" que j'écrirais plus petit...
> 
>     * je mettrais cote à cote profondeur et développement
> 
>     * Le nom de l'entry est parfois très long et ca rend pas génial dans ce cas car la police du nom est grosse (mais je n'ai pas de solution en tete...) -> https://orange-rock-0d4f87503-298.westeurope.azurestaticapps.net/ui/entrances/24610

C'est fait ! 

Pour le nom de l'entrée, la seule solution que je vois ce serait de le sortir du bloc latéral gauche et de le mettre dans un bloc qui prend toute la largeur tout en haut.

2021-12-17 10:15 UTC, merged