[ENTRANCE LOCATION] Add create location form
GrottoCenter/grottocenter-front pull request #408
Opened 2022-04-14 13:07 UTC by Clm-Roig

Fonctionnalités : 
- Bouton pour ouvrir le formulaire visible que si l'on est connecté
- Ajout dynamique de la nouvelle location à la suite des autres lorsque celle-ci est validée
- Fermeture du formulaire dans la foulée

2022-04-14 13:49 UTC, urien requested changes
Cela fonctionne parfaitement. pour éviter d'avoir une collection de boutons "Add a..." est ce qu'on pourrait mettre seulement un + a droite du titre "localisation" ?

2022-04-14 14:21 UTC, Clm-Roig commented
> Cela fonctionne parfaitement. pour éviter d'avoir une collection de boutons "Add a..." est ce qu'on pourrait mettre seulement un + a droite du titre "localisation" ?

Le truc c'est qu'en faisant ça on dissocie complètement le formulaire du bouton qui le fait apparaître. Dans le cas où il y a 5 ou 6 localisations, le formulaire sera tout en bas et le bouton tout en haut. 

Donc soit on met le bouton en haut comme tu le suggères et on remonte le formulaire en haut. 
Soit je fais un bouton plus discret tout en bas avec juste un plus.

2022-04-14 14:32 UTC, urien commented
Le fait de mettre le + a coté du titre de la rubrique fait que le lien entre le bouton et son rôle est immédiat. 

Je préfère que le formulaire soit en haut.

2022-04-14 15:26 UTC, Clm-Roig commented
C'est modifié. J'ai mis à jour les screens pour que tu voies le résultat avant que ce soit déployé @urien

2022-04-14 17:55 UTC, urien approved these changes
C'est parfait. Merci

2022-04-15 23:21 UTC, bsoufflet approved these changes

2022-04-15 23:21 UTC, bsoufflet commented on packages/web-app/src/components/appli/Form/CreateLocationForm/index.jsx
> +            helperText={error ? 'Un titre est requis' : ''}
Est il normal d'avoir le text en Francais ici ?

2022-04-15 23:24 UTC, bsoufflet commented
@Clm-Roig : N'y aurait il pas moyen de réduire un peu le choix dans le champ Language ? Car là on a vraiment trop de choses je pense... (ce n'est pas vraiment pour cette PR c'est pourquoi le l'ai déjà approved)
2 propositions : 
- Utiliser la colonne "is_preferred" pour filtrer et n'afficher que les quelques "preferred" langues
- utiliser la colonne "part1" pour n'afficher que les langues qui ont une valeurs "not null" dans cette colonne.

Je ne suis pas certain de à quoi la colonne "is_preferred" devait servir mais cette première solution me parait la plus logique et la plus élégante (quite à cocher quelques langues en plus si besoin). @urien  ?

2022-04-16 05:38 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Form/CreateLocationForm/index.jsx
> +            helperText={error ? 'Un titre est requis' : ''}
Non, c'est une erreur ! Je corrigerai ça merci

2022-04-16 05:40 UTC, Clm-Roig commented
On a parcouru le chemin inverse ces derniers mois justement. On a 16 (je crois) langues marquées comme préférées mais ça limitait les soumissions (un contributeur voulait soumettre en roumain notamment mais cette langue n'était pas marquée comme préférée). 

Donc j'ai développé l'autocomplete en conséquence... Il y a beaucoup de langues avec part1 non-vide ? J'ai pas fait trop attention à cette colonne, j'ai principalement bossé avec l'id et refName.

2022-04-16 05:47 UTC, urien commented
Je viens de faire un ticket ici https://github.com/GrottoCenter/Grottocenter3/issues/801

2022-04-19 07:12 UTC, bsoufflet approved these changes

2022-04-19 07:13 UTC, bsoufflet commented
@Clm-Roig : Ne serait il pas possible de mettre une valeur par défaut au champ langue en prenant la langue de l'utilisateur ?

2022-04-19 09:30 UTC, Clm-Roig commented
> @Clm-Roig : Ne serait il pas possible de mettre une valeur par défaut au champ langue en prenant la langue de l'utilisateur ?

C'est fait. J'ai dû rajouter quelques données hardcodées à propos des langues pour pas qu'on ait à requêter l'API juste pour avoir l'objet "language" complet à partir de la locale sélectionnée.

2022-04-19 09:32 UTC, bsoufflet approved these changes

2022-04-19 09:32 UTC, bsoufflet commented
Top ! @Clm-Roig

2022-04-19 09:36 UTC, merged