340 massif edit
GrottoCenter/grottocenter-front pull request #426
Opened 2022-05-04 17:36 UTC by lageta

2022-05-10 10:48 UTC, Clm-Roig requested changes
Il y a eu un souci avec la commande de linting : elle a mis à jour les fichiers .json également alors qu'elle ne devrait pas... Il faudrait que tu annules ton commit de lint et que tu modifies la commande de linting que tu as utilisé pour ne s'appliquer qu'aux fichiers js, jsx, ts et tsx.

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/Massif.jsx
> +              }}
Il me semble que `onChange={onChange}` marcherait ici.

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/Massif.jsx
> +              }}
Il me semble que `onChange={onChange}` marcherait ici.

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +      <FormLabel>{formatMessage({ id: 'Location of the massif' })}</FormLabel>
"Location of the massif" ça fait penser à un point, un emplacement. 
Peut-être que "Massif area" correspond mieux pour expliciter le concept de surface que représente le polygone non ? En français par contre je vois pas comment traduire... "Zone du massif" c'est un peu bizarre....

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +import { EditControl } from 'react-leaflet-draw';
Tes dépendances ont été installés à la racine du repo, dans /package.json (alors qu'elles devraient être dans packages/web-app/package.json). 

Il faut que tu les supprimes du premier et que tu relances `yarn add react-leaflet-draw` dans /packages/web-app.

De manière générale, si vous devez faire un eslint-disable, vous nous demandez avant : il y a toujours une bonne raison et une solution pour ne pas le faire 😉

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Pas de eslint-disable => fixe ton tableau de dépendances plutôt (même si `onChange` est constant, il faut quand même le renseigner dedans : c'est le comportement attendu)

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Pas de eslint-disable => fixe ton tableau de dépendances plutôt

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +      // eslint-disable-next-line camelcase
Tu peux le désactiver au sommet du fichier pour pas te répéter avec 
```js
/* eslint-disable camelcase */
```

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/providers.js
> +  }
Je ne m'y connais pas trop en open street map mais n'est-ce pas un doublon de `\src\components\common\Maps\common\mapLayers.js` ?

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/lang/en.json
> +  "Basic Informations": "Basic Information",
Y a une typo ici (pluriel / singulier, sachant qu'il faut garder le singulier pour les deux).

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/lang/en.json
> +  "Description of the massif": "Description of the massif",
"Massif description"

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/lang/en.json
> +  "Location of the massif": "Location of the massif",
"Massif location"

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/lang/en.json
> +  "Title of the massif description": "Title of the massif description",
Massif description title

2022-05-10 10:48 UTC, Clm-Roig commented on packages/web-app/src/lang/fr.json
>    "BBS document submission form": "Formulaire d'ajout de document BBS",
Pas de traductions dans tes PR ! On gère ça via Transifex, une plateforme dédiée.

2022-05-10 10:49 UTC, Clm-Roig commented
En cas d'erreur à la création d'un massif, je suis bloqué sur le spinner qui tourne indéfiniment si jamais l'API me retourne une erreur  403.

2022-05-10 10:52 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +  }),
Tu n'as pas utilisé cet attribut. Ce serait bien de gérer au moins le cas où le polygon est absent : 
![image](https://user-images.githubusercontent.com/20704943/167612552-745fad88-b584-4080-927d-ad526b0ac29f.png)

2022-05-10 12:19 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +      <FormLabel>{formatMessage({ id: 'Location of the massif' })}</FormLabel>
Je valide Massif area c'est plus pertinent, en français ça pourrait donner : "Aire du massif"?

2022-05-10 12:57 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Si je fixe mon tableau j'ai plusieurs erreurs dans la console 
![image](https://user-images.githubusercontent.com/74241345/167633604-ef7d99c7-0760-4115-ae26-c950e5877919.png)

![image](https://user-images.githubusercontent.com/74241345/167633440-e678f33f-1d6e-4c19-b5e2-a612c12a1e24.png)

2022-05-10 12:59 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
je peux en revanche enlever le tableau de dépendances non ? 
![image](https://user-images.githubusercontent.com/74241345/167633917-197d9b92-440f-4335-811d-b124f7113364.png)

Et je n'ai pas l'erreur comme ça.

2022-05-10 13:14 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
N'essaie pas d'aller contre eslint, il connaît mieux React et JS que nous ! D'ailleurs il a un bon conseil pour nous dans ce genre de cas (à tester) : 
![eslint](https://user-images.githubusercontent.com/20704943/167636187-181da644-e7bc-4a64-8096-187eedaa16c2.png)

Plutôt que de vider le tableau et de devoir le disable, tu peux retirer le tableau. 

Autre possibilité, c'est d'inclure les 2 dépendances. Ce n'est pas useEffect le problème. Je dirais que c'est que onChange change à chaque fois. useEffect s'exécute, appelle onChange. Ce qui modifie le parent de Polygon. Donc le parent de Polygon se rerender et fait se rerender Polygon peut-être. 
Mais pour le savoir ça, il faut débugguer et suivre les renders des composants pour en être sûr.

2022-05-10 13:16 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +      <FormLabel>{formatMessage({ id: 'Location of the massif' })}</FormLabel>
Pourquoi pas oui. On modifiera si besoin mais Aera / Aire est déjà plus pertinent que Location / Localisation.

2022-05-10 13:20 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Si je met rien dans mon tableau j'ai le même problème de boucle infini.
Le truc c'est que je fais du react depuis 1 semaine :/ je sais pas trop comment faire pour debugger ces problèmes de render

2022-05-10 13:25 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Je vais regarder, c'est vrai que c'est un des aspects les plus techniques de React ça ^^

2022-05-10 13:27 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +  }),
tu veux dire l'utiliser de cette manière ? 
![image](https://user-images.githubusercontent.com/74241345/167639481-c26fd7ca-a5e3-429c-a4c0-7c5d6f7cf14c.png)

2022-05-10 13:30 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +  }),
Oui en gros c'est ça (à voir pour les détails une fois implémenté).

2022-05-10 13:36 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Merci beaucoup ^^ c'est vrai que ça me change pas mal d'angular

2022-05-10 13:49 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Hum chez moi le fait de remplir le tableau avec `[mapLayers, onChange]` fonctionne parfaitement.

2022-05-10 13:52 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +      // eslint-disable-next-line camelcase
J'ai trouvé mieux sinon plutôt que de disable eslint (encore ^^). 

Tu peux faire ça :

2022-05-10 13:56 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Tiens c'est étrange ça, rien dans la console du navigateur quand tu crées un polygon ? et tu arrives à passer à la revue de données ?

2022-05-10 13:59 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Ouep' sur Firefox et sur Chrome.

2022-05-10 13:59 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Et ça marche aussi pour le deuxième useEffect avec [geolocation, map]);

2022-05-10 14:01 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
J'ai pas pensé que ça pouvait venir du navigateur, je suis sur brave !

2022-05-10 14:01 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Bon bah super je fais les modifications alors !

2022-05-10 14:07 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Ah ouais développer sur Brave c'est... courageux si je puis dire 😅 
Mais même, je comprends pas. Brave est basé sur Chromium, ça devrait pas poser de souci... Si tu peux retester au cas où, sur un autre navigateur ainsi que sur Brave avec tout de clean (navigation privée voire même rm-rf les modules et yarn), ce serait top 🙂

2022-05-10 14:09 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/Polygon.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Oula dans quoi je me suis engagé ah ah 😅 je vais faire mon maximum en tout cas 🙂

2022-05-10 14:11 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +  }),
Juste comment je peux tester ce cas maintenant que j'ai implémenté la gestion de l'erreur ?

2022-05-10 14:12 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +  }),
Si tu as l'API qui tourne, sur la partie "checkRight" de ta route, remplace `if(!hasRight)` par `if(true)` par exemple

2022-05-10 14:18 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonContainer.jsx
> +  }),
Ah oui d'accord je suis sur l'api de production là, je vais switch.

2022-05-10 14:55 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/PolygonMap/providers.js
> +  }
C'est vrai ! J'en ai profité pour ajouter toute les vues à la map

2022-05-10 15:46 UTC, lageta commented
> En cas d'erreur à la création d'un massif, je suis bloqué sur le spinner qui tourne indéfiniment si jamais l'API me retourne une erreur 403.

Je me suis basé sur cette PR https://github.com/GrottoCenter/grottocenter-front/pull/56 est-ce qu'il y a la même erreur pour le cas des entrées ?

2022-05-10 15:52 UTC, lageta commented
> Il y a eu un souci avec la commande de linting : elle a mis à jour les fichiers .json également alors qu'elle ne devrait pas... Il faudrait que tu annules ton commit de lint et que tu modifies la commande de linting que tu as utilisé pour ne s'appliquer qu'aux fichiers js, jsx, ts et tsx.

Si je fais l'interactive rebase 
![image](https://user-images.githubusercontent.com/74241345/167670442-cfb44237-328a-4403-9045-35fc1bdb5b1f.png)
je pourrai faire en sorte de garder mes changements, sauf les fichiers JSON ?

2022-05-10 16:00 UTC, Clm-Roig commented
Concernant le linting, oui. Tu peux lancer l'interactive rebase, drop le commit de lint puis valider.
Ensuite tu changes la config dans package.json. Puis tu relintes derrière.

2022-05-10 16:01 UTC, Clm-Roig commented
> > En cas d'erreur à la création d'un massif, je suis bloqué sur le spinner qui tourne indéfiniment si jamais l'API me retourne une erreur 403.
> 
> Je me suis basé sur cette PR #56 est-ce qu'il y a la même erreur pour le cas des entrées ?

Possible que ça plante aussi pour les entrées, je ne sais pas.

2022-05-10 16:43 UTC, lageta commented
> Concernant le linting, oui. Tu peux lancer l'interactive rebase, drop le commit de lint puis valider. Ensuite tu changes la config dans package.json. Puis tu relintes derrière.

Bon normalement c'est bon, git kraken n'a pas de fonction pour edit les commits lors de l'interactive rebase j'ai du tout faire dans le terminal  🥲

2022-05-10 20:14 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                : 'An error occur when updating a massif!'
"occurred"

2022-05-10 20:14 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                id: 'Retry'
"Reset" non plutôt ?

2022-05-10 20:15 UTC, Clm-Roig reviewed
Le code est bon pour moi, je teste la fonctionnalité en profondeur soit un peu plus tard dans la soirée soit demain. Beau boulot 🎉

2022-05-10 20:18 UTC, lageta commented
> Le code est bon pour moi, je teste la fonctionnalité en profondeur soit un peu plus tard dans la soirée soit demain. Beau boulot 🎉

Merci c'était fun de faire cette carte interactive 😄

2022-05-10 21:55 UTC, Clm-Roig commented
J'ai toujours le souci du chargement infini quand le serveur renvoie une 403. Y a un souci avec Redux, j'ai trouvé : je te mets des commentaires directement là où ça coine.

2022-05-10 21:55 UTC, Clm-Roig commented on packages/web-app/src/actions/Massif.js
> +export const UPDATE_MASSIF_FAILURE = '';
Il manque 'UPDATE_MASSIF_FAILURE' ici !

2022-05-10 21:56 UTC, Clm-Roig commented on packages/web-app/src/actions/Massif.js
> +  type: UPDATE_MASSIF_FAILURE,
POST_MASSIF_FAILURE ici

2022-05-10 22:05 UTC, Clm-Roig commented on packages/web-app/src/actions/Massif.js
> +  type: UPDATE_MASSIF_FAILURE,
Je m'en suis occupé, c'est corrigé !

2022-05-10 22:05 UTC, Clm-Roig commented on packages/web-app/src/actions/Massif.js
> +export const UPDATE_MASSIF_FAILURE = '';
Je m'en suis occupé, c'est corrigé !

2022-05-10 22:09 UTC, Clm-Roig commented
J'ai aussi amélioré la gestion de l'erreur du polygone et ajouté un petit texte d'explication au passage 🙂

2022-05-10 22:11 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                : 'An error occur when updating a massif!'
Corrigé.

2022-05-11 12:58 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                id: 'Retry'
C'est le bouton quand un erreur est survenue lors du submit non ? Il reset le formulaire mais au dessus c'est utilisé pour créer un nouveau massif donc je me suis dis qu'en cas d'échec ça serai l'équivalent à "Réessayer"
![image](https://user-images.githubusercontent.com/74241345/167855318-1eb77c9c-b9aa-4332-87ae-4cd1bdea5d88.png)

2022-05-11 16:21 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                id: 'Retry'
Je comprends pas : 
>  Il reset le formulaire [...] en cas d'échec ça serai l'équivalent à "Réessayer"

Pourquoi pas avoir un bouton réessayer oui. Mais comment il peut "réessayer" alors que son "onClick" c'est handleReset ? Le onClick est à changer alors.

2022-05-11 16:28 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                id: 'Retry'
On peut changer la fonction dans le onClick mais ça sera la même que le reset non ? 
![image](https://user-images.githubusercontent.com/74241345/167900442-78338ee5-94b0-466a-b097-1cb492f30de8.png)

2022-05-11 16:29 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                id: 'Retry'
Si tu regardes juste en haut le bouton c'est `'Create a new massif'` et pourtant il a aussi handleReset dans son onClick

2022-05-11 16:46 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                id: 'Retry'
Dans un premier temps, je n'ai même pas regardé le code de handleReset. C'est juste incohérent d'avoir un bouton "Retry" et "Create new massif" dont la fonction onClick est "handleReset" : y a forcément un problème de nommage quelque part. 

Sans exécuter le code, je ne comprends même pas comment le "Create new massif" arrive à créer un nouveau massif alors qu'il appelle handleReset et qu'il n'est pas de type submit... Y a quelque chose qui cloche niveau cohérence et lisibilité quoi qu'il arrive, c'est pas clair.

2022-05-11 16:54 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                id: 'Retry'
Là on parle des boutons qui s'affichent quand le submit a été effectué :
-si la création du massif est un succès, il y a le bouton Create a new massif qui apparaît qui réaffiche le formulaire vierge pour créer un nouveau massif 
-si la création du massif est un échec je voulais remplacer ce bouton par un bouton Retry

2022-05-11 17:00 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +                id: 'Retry'
Ah mais oui, merci ! Désolé j'avais mal vu le niveau d'indentation. Dans ce cas-là, c'est bon pour moi.

2022-05-11 17:01 UTC, Clm-Roig approved these changes

2022-05-11 17:09 UTC, merged