18 person view
GrottoCenter/grottocenter-front pull request #443
Opened 2022-05-09 20:34 UTC by VivienLvr

fix #18

2022-05-09 22:32 UTC, Clm-Roig requested changes
C'est du beau boulot dans l'ensemble, bien joué ! Demain je serai joignable sur Slack toute la journée pour discuter de mes retours si tu as besoin :wink:

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              <CardContent>
En Material Design, on évite d'avoir une carte sur une carte. La page est déjà une "Card", il faut éviter de remettre une carte dessus, surtout aussi grosse :slightly_smiling_face:

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +      title={`Page profil de l'utilisateur ${person.name} ${person.surname}`}
`Profil de l'utilisateur` doit être traduisible. Je pense que tu peux ajouter un séparateur entre utilisateur et person.name (un tiret ou deux points par exemple)

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +                  Documents
A traduire (voir l'utilisateur de formatMessage() et useIntl() dans d'autres composants).

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +                <Typography color="textPrimary" variant="h3" gutterBottom>
Il me semble que `textPrimary` n'existe pas comme color pour Typography : le titre est noir d'ailleurs.

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +  if (person == null) {
=== plutôt que ==

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +      <h3>
`Typography variant="h3"` plutôt

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +        </Translate>
L'erreur s'affiche même pendant le chargement des données, doit y avoir un souci avec la gestion du null / undefined.

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +      return entry;
Tu peux faire ça en une seule ligne : 
```js
person.exploredEntrances.map(entrance => ({
  ...entrance,
  name: entrance.name ? entrance.name: 'no name'
})
```

:warning: Cela dit, je pense que ce n'est pas à ce composant de gérer le nom de l'entrée. C'est la liste qui doit choisir comment gérer l'absence de nom, pas ton composant Person :slightly_smiling_face:

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +                  })}
Tu peux raccourcir : 
```js
docs={person.documents.map(doc => ({ ...doc, title: doc.descriptions[0].title }));
```

`=> (` remplace le return :wink:

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/AppBar/User.jsx
> +  const accountPath = useRef('/ui');
Pourquoi utiliser une ref ici ? Je n'en vois pas l'intérêt mais je rate peut-être quelque chose...

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/AppBar/User.jsx
> +  const redirectPersonPage = () => {
Le terme "redirect" ne me paraît pas approprié ici. La redirection c'est quand on redirige quelqu'un qui va déjà quelque part. Là, tu amènes l’utilisateur quelque part comme prévu.

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/DocumentsList/DocumentsList.jsx
> +const StyledList = withStyles({
Utilise `styled(List)` plutôt. Ton code est bon en soit, c'est juste une convention sur Grottocenter que de passer par styled plutôt que withStyles.

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/DocumentsList/DocumentsList.jsx
> +        <em>{emptyMessageComponent}</em>
`emptyMessageComponent` est un composant. Je pense donc qu'il ne devrait pas être placé entre des balises <em> pour laisser un maximum de contrôle au composant qui passe le `emptyMessage` qui, lui, se chargera de mettre en gras s'il le veut.

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/Organizations/OrganizationsList.jsx
> +const StyledList = withStyles({
styled

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/Organizations/OrganizationsList.jsx
> +        <em>{emptyMessageComponent}</em>
em à supprimer

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +    });
En combinant .map() et .join() (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/join), tu peux écrire ça en une ligne de manière plus concise : 
- Avec map() tu construis un tableau de String avec que les noms
- Avec join(), tu les concatènes avec la virgule (et ça gère le fait qu'il n'y a pas de virgules à la fin :wink: )

2022-05-09 22:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +    <div style={{ display: 'flex', flexDirection: 'column' }}>
Mui a un composant "Box" https://v4.mui.com/components/box/ à utiliser à la place de div, avec notamment des raccourcis pour en faire une flexbox.

2022-05-10 07:45 UTC, VivienLvr commented on packages/web-app/src/components/appli/Person/Person.jsx
> +        </Translate>
Le === au lieu de == a corrigé ce problème.

2022-05-10 07:49 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +        </Translate>
Super ! Tu peux "Resolve" mes commentaires une fois que tu les as résolus 🙂

2022-05-10 11:03 UTC, VivienLvr commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              <CardContent>
J'aurais aimé avoir des séparateurs physiques entre chaque bloc de la page (infos, documents, organisations et entrées). Comment je pourrais faire ça autrement ? Un simple <hr /> peut marcher mais c'est moins beau que les cards de material.

2022-05-10 11:09 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              <CardContent>
Le <hr> j'aime bien perso. 

Sinon tu peux faire comme sur la page d'une entrée (à droite) et faire une carte par section, sans carte dans le background : https://grottocenter.org/ui/entrances/20

2022-05-10 11:15 UTC, VivienLvr commented on packages/web-app/src/components/common/AppBar/User.jsx
> +  const accountPath = useRef('/ui');
C'est un moyen que j'ai trouvé pour faire un lien mais j'imagine qu'il y a mieux à faire. C'est suffisant de faire juste comme ça ? 
`const redirectPersonPage = () => {
    history.push(`/ui/persons/${userId}`);
  };`

2022-05-10 11:19 UTC, VivienLvr commented on packages/web-app/src/components/common/AppBar/User.jsx
> +  const redirectPersonPage = () => {
Comment je pourrais l'appeler pour que ce soit plus logique ?

2022-05-10 11:41 UTC, VivienLvr commented on packages/web-app/src/components/common/DocumentsList/DocumentsList.jsx
> +const StyledList = withStyles({
J'ai essayé cette syntaxe mais elle ne semble pas fonctionner : 
<img width="614" alt="Capture d’écran 2022-05-10 à 13 40 59" src="https://user-images.githubusercontent.com/30286062/167620492-68c85349-9f65-4991-b8e2-35fe357d3ad4.png">

2022-05-10 13:05 UTC, Clm-Roig commented on packages/web-app/src/components/common/AppBar/User.jsx
> +  const redirectPersonPage = () => {
`handleMyAccountClick`. C'est un handler de click tout comme `handleLogoutClick` juste au-dessus 😉

2022-05-10 13:06 UTC, Clm-Roig commented on packages/web-app/src/components/common/AppBar/User.jsx
> +  const accountPath = useRef('/ui');
Oui ça marcherait. On a des history.push un peu partout dans tout le code qui n'utilise pas de ref sans aucun souci.

2022-05-10 13:08 UTC, Clm-Roig commented on packages/web-app/src/components/common/DocumentsList/DocumentsList.jsx
> +const StyledList = withStyles({
Point virgule à la fin de chaque ligne, comme du css "traditionnel".

2022-05-10 15:58 UTC, urien commented
Je suis en train de tester... Cela va être super !
Je suis un contributeur avec beaucoup de documents, est ce qu'il serait possible mettre un autre message en attendant que les données se chargent ?
![image](https://user-images.githubusercontent.com/1165144/167671549-10827579-9b0c-4f35-8da5-3d38f10d2e6d.png)

2022-05-10 16:21 UTC, VivienLvr commented
> Je suis en train de tester... Cela va être super !
> Je suis un contributeur avec beaucoup de documents, est ce qu'il serait possible mettre un autre message en attendant que les données se chargent ?
> ![image](https://user-images.githubusercontent.com/1165144/167671549-10827579-9b0c-4f35-8da5-3d38f10d2e6d.png)

Ce message n’était pas censé s’afficher pendant le chargement mais l’erreur a été corrigée. Dès que j’ai fini de corriger le reste, j’enverrai ça sur github et vous pourrez tester sans bug.

2022-05-10 16:23 UTC, VivienLvr commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              <CardContent>
D’accord je vais mettre des hr, ça sera bien.

2022-05-12 05:32 UTC, urien commented
Super, pour les utilisateurs c'est plus clair.
J'ai demandé aux membres du CA de faire des tests et un autre pb est apparu. Quand on n'est pas connecté on reste sur une page blanche. Je ne sais pas si c'est côté front ou back. Normalement la visualisation des pages des personnes est possible sans connexion

2022-05-12 06:20 UTC, Souterweb commented
Le 12/05/2022 à 07:33, Urien a écrit :
> Super, pour les utilisateurs c'est plus clair.
> J'ai demandé aux membres du CA de faire des tests et un autre pb est 
> apparu. *Quand on n'est pas connecté on reste sur une page blanche*. 
> Je ne sais pas si c'est côté front ou back. Normalement la 
> visualisation des pages des personnes est possible sans connexion

Ave,

Je ne comprends pas la phrase en gras ci-dessus.

Quand je ne suis pas connecté, si je clique sur l'icône S'IDENTIFIER 
j'arrive sur la petite fenêtre d'identification.
Il n'y a ni page blanche, ni possibilité de visualiser les personnes.

Domi

2022-05-12 06:40 UTC, urien commented
Il faut pouvoir voir la page de toutes les personnes sans s'identifier. Actuellement cela ne fonctionne pas

2022-05-12 07:38 UTC, Clm-Roig requested changes

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +        ) : (
Le composant Skeleton permet d'utiliser un composant enfant pour avoir une approximation de sa taille plutôt que de lui spécifier une hauteur fixe :arrow_right: https://v4.mui.com/components/skeleton/#inferring-dimensions

C'est plus pertinent car le principe du squelette c'est de faire percevoir à l'avance à l'utilisateur quelles zones vont être remplies : si le Skeleton ne correspond pas au contenu, cet effet est fortement réduit et pénalise l'expérience utilisateur :slightly_smiling_face:

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +  }
Tu peux le déplacer plus bas, dans le return, avec l'autre Skeleton : 
```js
isFetching || person === undefined ? (
    <Skeleton ...
) : (
```

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +      </Typography>
A déplacer dans le return pour bénéficier de la mise en page du Layout. Là, l'erreur s'affiche sur fond blanc, c'est pas super esthétique. Je pense aussi que si tu arrives à `person === null`, tu as forcément une erreur à afficher : chose qui n'est pas fait ici. 

Dernière petit chose : je mettrais bien ce message dans un composant `common/Alert` avec une severity "error" pour bien le différencier du texte classique.

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/common/DocumentsList/DocumentsList.jsx
> +    <div>
Utilise les React.fragment plutôt que des divs : c'est le symbol `<></>`

Doc : https://reactjs.org/docs/fragments.html

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/common/Organizations/OrganizationsList.jsx
> +    <div>
React fragment (<> </>)

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +  <div>
React Fragment (<></>)

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +    nickname: PropTypes.string,
id et nickname sont à marquer "required"

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/common/entrance/EntranceListItem.jsx
> +        primary={entrance.name ? entrance.name : 'no name'}
"no name" serait à traduire normalement. 

Mais je trouve pas ça très user friendly d'afficher "no name" de la même façon qu'un nom classique. Il faut soit l'afficher en italique et dans une autre couleur (gris ?) soit ne pas l'afficher. Sinon on ne comprend pas en terme d'UX que c'est une valeur nulle derrière.

2022-05-12 07:38 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              })}
**[valable pour tous les emptyMessageComponent de ce fichier]**

A wrapper, au minimum, dans un `<Typography />`, sinon dans un `<Alert severity="info">`.

2022-05-12 11:45 UTC, VivienLvr commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +  <div>
Le problème c'est que ça a changé totalement l'affichage d'enlever la div 
<img width="476" alt="Capture d’écran 2022-05-12 à 13 40 05" src="https://user-images.githubusercontent.com/30286062/168066957-540c2e65-32c5-4fbf-a1b2-932ad1466753.png">

2022-05-12 11:51 UTC, Clm-Roig commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +  <div>
Alors c'est peut-être une <Box> qu'il te faut dans ce cas-là. C'est plus flexible qu'une div.

2022-05-12 12:21 UTC, VivienLvr commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +  <div>
@ClemRz Une quoi ? Ça ne s'est pas affiché

2022-05-12 12:22 UTC, Clm-Roig commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +  <div>
https://v4.mui.com/components/box/

2022-05-12 13:04 UTC, VivienLvr commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              })}
C'est mieux de le faire dans ce composant ou dans les composants de chaque liste ?

2022-05-12 13:05 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              })}
Dans le composant de chaque liste. Le nom de la prop étant "emptyMessageComponent", on s'attend à pouvoir passer n'importe quoi sans que le composant n'effectue de modification dessus.

2022-05-12 13:07 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              })}
Ou sinon, si on s'en sert vraiment tout le temps de la même manière, tu le fais dans le composant et tu renommes `emptyMessageComponent` par `emptyMessage` et tu le fais devenir une string. Comme ça tout nos emptyMessages sont les mêmes.

À toi de voir selon les cas d'utilisation à travers toute l'application 😉

2022-05-12 13:14 UTC, VivienLvr commented on packages/web-app/src/components/appli/Person/Person.jsx
> +              })}
D'accord je vais y réfléchir.

2022-05-12 14:47 UTC, VivienLvr commented
> Il faut pouvoir voir la page de toutes les personnes sans s'identifier. Actuellement cela ne fonctionne pas

C'était une erreur. Je l'ai résolue dans mon dernier commit.

2022-05-12 16:48 UTC, urien commented
Super bien ! bravo !

2022-05-13 12:20 UTC, Clm-Roig requested changes
Je pushe quelques modifs mineures en plus, n'hésite pas à me dire si ça te convient pas @VivienLvr : 
- changement de "isAllowed" par "canEdit" (plus précis)
- modification du FlexBlock pour en faire une Box et réduction de ses margins
- modification du bouton d'édition pour qu'il soit sur la même ligne que les informations de l'utilisateur

2022-05-13 12:20 UTC, Clm-Roig commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +  displayGroups
Je m'interroge sur l'utilité de ses displays. Est-ce que ce n'est pas plutôt au parent de retirer à `person` les attributs qu'on ne veut pas voir affiché ? Auquel cas il suffit de changer le code par : 
```js
      {person.language && (
        <UserProperty
          propertyName={formatMessage({ id: 'Language' })}
          value={person.language}
        />
      )}
```

Je pense au cas où l'utilisateur courant ne doit pas voir le mail d'un autre utilisateur. L'API ne le renverra pas et donc on aura person.mail qui sera undefined.

2022-05-13 12:20 UTC, Clm-Roig commented on packages/web-app/src/pages/Person/index.jsx
> +      onEdit={onEdit}
On est d'accord que l'edit n'est pas encore implémenté ? Auquel cas il faudrait commenter cette ligne en le précisant et en expliquant que tout est prêt dans ce composant pour quand l'edit sera prêt.

2022-05-13 12:29 UTC, VivienLvr commented on packages/web-app/src/pages/Person/index.jsx
> +      onEdit={onEdit}
Non l'edit n'est pas encore prêt

2022-05-13 12:36 UTC, VivienLvr commented on packages/web-app/src/components/common/Person/PersonProperties.jsx
> +  displayGroups
Effectivement ça me paraît plus logique de faire comme ça

2022-05-13 12:42 UTC, VivienLvr commented on packages/web-app/src/pages/Person/index.jsx
> +      onEdit={onEdit}
Du coup je dois commenter tout ce qui se rapporte à l'édit pour qu'il n'y ait pas d'erreur non ?

2022-05-13 12:43 UTC, Clm-Roig commented on packages/web-app/src/pages/Person/index.jsx
> +      onEdit={onEdit}
Oui exactement, pour ne pas contrarier eslint 🙂

2022-05-15 05:22 UTC, urien commented
Il me semble qu'on pourrait publier ce travail, non ?

2022-05-15 08:27 UTC, Clm-Roig approved these changes

2022-05-15 08:27 UTC, Clm-Roig commented
> Il me semble qu'on pourrait publier ce travail, non ?

Je n'avais pas encore approuvé les derniers changements, c'est chose faite 🙂

2022-05-15 08:44 UTC, merged

2022-05-23 22:18 UTC, bsoufflet commented
@urien @Clm-Roig : Je me rend compte que le terme "cavities" (caries en francais) est revenu dans grottocenter avec cette PR :( Il faudrait peut etre faire un petit fix pour corriger ;)

2022-05-24 06:48 UTC, urien commented
J'ai fait une pr https://github.com/GrottoCenter/grottocenter-front/pull/476