fix(search): issue #301 invert button in search
GrottoCenter/grottocenter-front pull request #446
Opened 2022-05-13 10:59 UTC by hafidinferno

2022-05-13 12:23 UTC, Clm-Roig commented
Les déploiements de "preview" sont bloqués pour le moment car on a déjà 3 Pull Requests actives. Dès qu'on en merge une, je review celle-ci :slightly_smiling_face:

2022-05-16 17:21 UTC, Clm-Roig requested changes

2022-05-16 17:21 UTC, Clm-Roig commented on .vscode/launch.json
> +}
A supprimer, on ne versionne pas les fichiers vscode

2022-05-16 17:21 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Properties.jsx
> +          label={formatMessage({ id: '' })}
C'est hors Pull request et ça fait planter l'application (on ne peut pas passer un id vide à traduire), c'est à supprimer.

2022-05-16 17:28 UTC, Clm-Roig commented
Il y a un souci sur les accordéons ; avant lorsque l'on en ouvrait un, ça fermait l'autre. Plus maintenant. 
Il y a eu un problème lors de l'inversion des deux accordéons, les ids ne matchent plus : 

```jsx
<Accordion
 expanded={panelExpanded === 'all-fields-panel'}   // <-------- ici on a 'all-fields-panel'
            onChange={this.handlePanelSelected('all-fields-panel')}> // <-------- ici aussi
            <AccordionSummary
              expandIcon={<ExpandMoreIcon />}
              aria-controls="specific-fields-search-content" // <-------- là on est sur "specific-fields"
              id="specific-fields-search-content"> //  <-------- là aussi
```

2022-05-18 11:37 UTC, urien commented
@hafidinferno est-ce qu'il est possible de corriger rapidement, suite aux remarques de Clément ? Cela permettrait de finaliser cette PR et de publier le code

2022-05-18 12:54 UTC, hafidinferno commented
Bonjour monsieur ;
J'ai reglé le problème selon la solution de Clement mais le problème est
que visual studio ne compile pas le code quand j'inverse les accordions et
je voulais voir avec Benjamin pour trouver une solution a ce soucis.

On Wed, May 18, 2022, 13:38 Urien ***@***.***> wrote:

> @hafidinferno <https://github.com/hafidinferno> est-ce qu'il est possible
> de corriger rapidement, suite aux remarques de Clément ? Cela permettrait
> de finaliser cette PR et de publier le code
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GrottoCenter/grottocenter-front/pull/446#issuecomment-1129900625>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ4PRIPFCRIC3R6P2O2DH63VKTJB7ANCNFSM5V3AYXVA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-18 12:58 UTC, urien commented
Est ce que vous l'avez sollicité ?

2022-05-18 12:59 UTC, urien commented
Est ce qu'il ne suffit pas de faire un commit et de relancer le front ?

2022-05-18 15:33 UTC, closed without merging