341 organzation create edit
GrottoCenter/grottocenter-front pull request #447
Opened 2022-05-13 12:26 UTC by lageta

fix #340 

J'ai implémenté des features comme, l'uploader, le numéro de téléphone, la deuxième adresse… qui ne sont pas encore compatible avec le back. Comme je n'aurai pas le temps de modifier ce dernier, les features sont commentés pour qu'elles soient déjà disponible le jour où les changements seront faits.

Elles sont néanmoins testables !
L'uploader à néanmoins un petit soucis pour garder en mémoire qu'on lui donne un fichier (on ne peut pas utiliser simplement useWatch car avec la propriété onChangeStatus du composant cela créé une boucle infini.

2022-05-15 19:48 UTC, lageta commented
Lors de la création d'une organisation, le langage n'est pas pris en compte à cause d'une petite erreur dans le back. Je créé une issue pour fix ce bug.

2022-05-17 04:10 UTC, urien commented
Super, la création fonctionne parfaitement.
Le message sur les licences apparait sur les 2 dernières fenetre. Ce serait mieux si elle n'était présente que sur la derniere
Bravo,

2022-05-17 04:55 UTC, urien commented
L'édition fonctionne aussi très bien

2022-05-17 12:37 UTC, Clm-Roig requested changes

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/actions/CreateOrganization.js
> +export const postOrganization = data => {
Le passage du paramètre "name" en "data" a cassé la création simple d'organisation dans la soumission de documents. 

Il est primordial que tu vérifies que ta fonction n'est jamais utilisée ailleurs avant d'en changer sa signature 😉

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/BasicInformationsForm.jsx
> +  }, [permissions, history]);
Tu peux utiliser le composant AuthChecker dont c'est exactement le rôle 🙂

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/License.jsx
> +  `;
A sortir du composant License et utiliser theme.spacing comme tu l'as fait pour le style(MuiFormControl).

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/License.jsx
> +            id: 'The following licenses will apply to your contribution'
Il manque un point ou deux points à la fin de ce message.

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Location/Position.jsx
> +          style={{ borderRadius: '4px', margin: '4px' }}
A sortir dans un styled composant.

- Pour border-radius : theme.shape.borderRadius,
- Pour margin : theme.spacing

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Location/index.jsx
> +const Location = ({ control, errors }) => {
Ce composant devrait s'appeler "Position" je pense. "Location" désigne les descriptions de localisations qu'on retrouve sur les entrées de cavité.

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Location/index.jsx
> +  };
Ces fonctions existent déjà dans le composant Entrance. A refactoriser et à mettre en commun dans un dossier /utils (au même niveau que /hooks).

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Uploader.jsx
> +  }, [permissions, history]);
`<AuthChecker />`

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Uploader.jsx
> +  const LOGO_SIZE_IN_BYTES = 10485760; // 10MB
A renommer `MAX_ORGANIZATION_LOGO_SIZE_IN_BYTES ` et à placer dans config/Config.js

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/pages/Application.jsx
> +          path="/ui/organizations/edit/:organizationId"
organizations/:organizationId/edit (comme discuté sur une autre PR)

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/pages/EntityEdit/Organization/OrganizationEditContainer.jsx
> +        Error, the massif data you are looking for is not available.
"the organization data"

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/pages/EntityEdit/Organization/OrganizationEditContainer.jsx
> +  `;
A sortir du composant + c'est mal nommé. Un padding de 10% ne centre pas par définition, il ajoute juste du padding.

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/reducers/OrganizationPostReducer.js
> +        data: action.cave,
.organization il me semble ?

2022-05-17 12:37 UTC, Clm-Roig commented on packages/web-app/src/reducers/OrganizationPutReducer.js
> +        data: action.cave,
.organization non ?

2022-05-18 09:26 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Organization/BasicInformationsForm.jsx
> +  }, [permissions, history]);
AuthChecker peut aussi vérifier que l'utilisateur est un admin ?

2022-05-18 10:48 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/BasicInformationsForm.jsx
> +  }, [permissions, history]);
Non mais il pourrait être modifié pour le faire. Son code n'est pas très compliqué et peut évoluer facilement.

2022-05-23 15:50 UTC, urien commented
Cela fonctionne bien ! Merci

2022-05-24 07:41 UTC, Clm-Roig requested changes
Dernière ligne droite, tu y es presque :wink:

2022-05-24 07:41 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/BasicInformationsForm.jsx
> +  }, [permissions, history]);
Je crois que ce commentaire n'a pas été résolu vu le code (il reste toujours le useEffect avec if(!permissions).

2022-05-24 07:41 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Position/index.jsx
> +  setFocus: PropTypes.func
Prop non-utilisée => à supprimer

2022-05-24 07:41 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Position/index.jsx
> +  control: PropTypes.shape({}),
Ajouter `.isRequired` sur cette prop

2022-05-24 07:41 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Uploader.jsx
> +                    : formatMessage({ id: 'Drag your logo' })
J'aurais plutôt dit `Drag and drop your logo here` ici, ce serait plus précis.

2022-05-24 07:41 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Organization/Uploader.jsx
> +  control: PropTypes.shape({}),
.isRequired

2022-05-24 08:24 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Organization/BasicInformationsForm.jsx
> +  }, [permissions, history]);
Effectivement en faisant un rebase je n'ai pas vu que ça avait remis ce if

2022-05-24 08:37 UTC, Clm-Roig requested changes

2022-05-24 08:37 UTC, Clm-Roig commented on packages/web-app/src/pages/EntityEdit/Organization/OrganizationEdit.jsx
> +    />
2 choses : 
- Je pense que tu peux fusionner OrganizationEdit & OrganizationEditContainer en un seul composant vu que celui-ci ne fait pas grand chose. 
- Tu n'a pas utilisé le AuthChecker au final : c'est voulu ?

2022-05-24 11:57 UTC, lageta commented on packages/web-app/src/pages/EntityEdit/Organization/OrganizationEdit.jsx
> +    />
- En effet on peut fusionner les deux 
- Oui c'est normal de ne plus utiliser AuthChecker (il était utilisé pour une variable isPartner mais vu que cette dernière n'est pas utilisée dans les requêtes de l'API j'ai simplement supprimé le champs au même titre que le numéro de telephone, le logo....)

2022-05-24 12:11 UTC, Clm-Roig approved these changes

2022-05-24 12:13 UTC, merged