345 organization view
GrottoCenter/grottocenter-front pull request #448
Opened 2022-05-14 11:46 UTC by VivienLvr

fix #345

2022-05-17 12:10 UTC, Clm-Roig requested changes

2022-05-17 12:10 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersList.jsx
> +import OrganizationListItem from './UsersListItem';
UserListItem

2022-05-17 12:10 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersList.jsx
> +              <OrganizationListItem key={user.id} user={user} />
UserListItem

2022-05-17 12:10 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersList.jsx
> +            .sort((a, b) => a.name.localeCompare(b.name))
Compare sur le nickname plutôt, c'est l'attribut a utilisé dès qu'on veut désigner un utilisateur.

Le name et surname ne sont affichés que sur la page d'un utilisateur, quand on veut des détails sur lui.

2022-05-17 12:10 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersList.jsx
> +  users: PropTypes.arrayOf(PropTypes.shape({})),
```js
users: PropTypes.arrayOf(
  PropTypes.shape({
    id:PropTypes.number,
    nickname: PropTypes.string,
  })
)
```

2022-05-17 12:10 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersListItem.jsx
> +            <>{user.nickname}</>
user.nickname uniquement

2022-05-17 12:10 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersListItem.jsx
> +        primaryTypographyProps={{ style: { whiteSpace: 'normal' } }} // Multiple lines text
Est-ce vraiment nécessaire ici ? Le nickname est court, même sur téléphone, ça ne risque pas de passer à la ligne il me semble (grâce au min-width: 250px).

2022-05-17 12:10 UTC, Clm-Roig commented on packages/web-app/src/lang/en.json
> +  "This organization has no documents listed yet.": "This organization has no document listed yet.",
Il manque un "s" à "document" à droite

2022-05-17 12:10 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Organization/RelatedCaves.jsx
> -  partnerNetworks: PropTypes.arrayOf(NetworkPropTypes)
Les entrées / réseaux partenaires ne sont plus affichés ? Une raison à cela ?

2022-05-17 12:56 UTC, VivienLvr commented on packages/web-app/src/components/common/UsersList/UsersListItem.jsx
> +        primaryTypographyProps={{ style: { whiteSpace: 'normal' } }} // Multiple lines text
Non c'est pas nécessaire, je l'ai copié de EntranceList et j'ai oublié de l'enlever.

2022-05-17 12:58 UTC, VivienLvr commented on packages/web-app/src/components/appli/Organization/RelatedCaves.jsx
> -  partnerNetworks: PropTypes.arrayOf(NetworkPropTypes)
J'ai demandé à @urien dans #345, il m'a conseillé de l'enlever pour le moment car le back n'est pas prêt.

2022-05-17 13:02 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Organization/RelatedCaves.jsx
> -  partnerNetworks: PropTypes.arrayOf(NetworkPropTypes)
Pour nuancer, le back est prêt sur les réseaux "partner" mais pas sur les entrées "partner". Bon par contre, même pour les réseaux, il y en a 0 dans la BD de prod actuellement. 

Merci pour la réponse, je ferme ce commentaire 🙂

2022-05-17 13:11 UTC, VivienLvr commented on packages/web-app/src/components/common/UsersList/UsersList.jsx
> +  users: PropTypes.arrayOf(PropTypes.shape({})),
Je dois les mettre required ?

2022-05-17 13:13 UTC, VivienLvr commented on packages/web-app/src/components/appli/Organization/RelatedCaves.jsx
> -  partnerNetworks: PropTypes.arrayOf(NetworkPropTypes)
Par contre j'aurais pu laisser le code commenté si l'implémentation est prévue.

2022-05-17 13:16 UTC, VivienLvr commented on packages/web-app/src/components/common/UsersList/UsersListItem.jsx
> +            <>{user.nickname}</>
C'est possible d'avoir un user sans nickname ? Je dois tester si ce n'est pas null avant de l'afficher ou pas besoin ?

2022-05-17 15:13 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersList.jsx
> +  users: PropTypes.arrayOf(PropTypes.shape({})),
Oui vaut mieux effectivement

2022-05-17 15:14 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersListItem.jsx
> +            <>{user.nickname}</>
Normalement non ce n'est pas possible. On devrait juste ajouter une contrainte en BD, je vais m'en occuper

2022-05-17 15:39 UTC, urien approved these changes
Comme utilisateur cela me plait beaucoup !
C'est magnifique !

2022-05-17 15:41 UTC, urien commented
@VivienLvr  est ce que ce n'est pas plus simple de mettre le bouton édition dès à présent ? Il suffira de publier la pull request sur l'édition des organisations avant de publier celle-ci

2022-05-17 15:47 UTC, VivienLvr commented
> @VivienLvr est ce que ce n'est pas plus simple de mettre le bouton édition dès à présent ? Il suffira de publier la pull request sur l'édition des organisations avant de publier celle-ci

Oui bien sûr je peux rendre le bouton fonctionnel vu que la page d'édit est également prête.

2022-05-17 15:48 UTC, VivienLvr commented
> Comme utilisateur cela me plait beaucoup ! C'est magnifique !

Super !

2022-05-17 16:08 UTC, urien commented
Du coup je vois un bouton 
![image](https://user-images.githubusercontent.com/1165144/168857746-9a7d2db8-74c2-4215-a38b-acb6d6cc5930.png)

Qui n'est pas actif. je pense qu'il vaut mieux utiliser le même composant que sur les autres pages , sans texte
![image](https://user-images.githubusercontent.com/1165144/168857964-ec309803-a14a-49fd-943f-99be23421f2a.png)

2022-05-17 16:44 UTC, VivienLvr commented
> Du coup je vois un bouton ![image](https://user-images.githubusercontent.com/1165144/168857746-9a7d2db8-74c2-4215-a38b-acb6d6cc5930.png)
> 
> Qui n'est pas actif. je pense qu'il vaut mieux utiliser le même composant que sur les autres pages , sans texte ![image](https://user-images.githubusercontent.com/1165144/168857964-ec309803-a14a-49fd-943f-99be23421f2a.png)

Personnellement je vois le bouton actif. Mais je peux enlever le texte si vous voulez.
<img width="1184" alt="Capture d’écran 2022-05-17 à 18 43 53" src="https://user-images.githubusercontent.com/30286062/168865130-9653b308-260f-4aac-aa24-3878ab3ca4a9.png">

2022-05-17 17:00 UTC, urien commented
Oui, il vaut mieux enlever le texte pour faire comme sur les documents ou les entrées.
Merci

2022-05-18 12:25 UTC, urien commented
la route est organizations/edit/id et non organizations/id/edit dans le travail d'Axel

2022-05-18 12:29 UTC, Clm-Roig commented
Cette organisation plante chez moi :
https://orange-rock-0d4f87503-448.westeurope.azurestaticapps.net/ui/organizations/2294

![image](https://user-images.githubusercontent.com/20704943/169038780-9b373659-64df-482c-8d2e-89c6845d5578.png)

2022-05-18 14:11 UTC, VivienLvr commented
> la route est organizations/edit/id et non organizations/id/edit dans le travail d'Axel

Je pensais que ça allait être changé au vu du commentaire que @Clm-Roig avait laissé sur sa PR.

2022-05-18 14:36 UTC, Clm-Roig commented
Oui oui il faut organizations/:id/edit ! 
Et faire la modif approprié dans Application.jsx qui gère les routes.

2022-05-18 14:39 UTC, VivienLvr commented
> Cette organisation plante chez moi : https://orange-rock-0d4f87503-448.westeurope.azurestaticapps.net/ui/organizations/2294
> 
> Elle a très peu de données, ça doit venir d'une valeur nulle pas bien gérée.
> 
> ![image](https://user-images.githubusercontent.com/20704943/169038780-9b373659-64df-482c-8d2e-89c6845d5578.png)

Le problème est réglé.

2022-05-19 08:21 UTC, Clm-Roig requested changes
Un dernier changement (mineur) et c'est tout bon 🙂 Beau travail 🎉

2022-05-19 08:21 UTC, Clm-Roig commented on packages/web-app/src/components/common/UsersList/UsersList.jsx
> +import OrganizationListItem from './UserListItem';
C'est UserListItem ici (et plus bas donc aussi)

2022-05-19 14:18 UTC, Clm-Roig approved these changes

2022-05-19 14:23 UTC, merged