340 edit massif
GrottoCenter/grottocenter-front pull request #451
Opened 2022-05-15 13:11 UTC by lageta

2022-05-15 17:36 UTC, urien approved these changes
Comme utilisateur cela fonctionne très bien.

2022-05-15 19:14 UTC, Clm-Roig commented
Je review demain matin normalement

2022-05-16 08:19 UTC, Clm-Roig commented
> add the route to edit massif at `/ui/massifs/edit/massifId`

La route appropriée est plutôt **/ui/massifs/:massifId/edit** : d'abord tu indiques le massif puis quelle action tu fais dessus (il me semble que c'est ce qu'on a fait pour les autres entités aussi non ?).

2022-05-16 10:44 UTC, urien commented
Pour les documents c'est https://grottocenter.org/ui/documents/edit/113207

2022-05-16 17:11 UTC, Clm-Roig commented
> Pour les documents c'est https://grottocenter.org/ui/documents/edit/113207

J'avais jamais fait attention mais ça ne me parait pas être un bon choix. Il faudrait corriger les deux selon moi si l'on veut se conformer à la norme REST (celle que l'on utilise pour l'API).

2022-05-16 18:03 UTC, Clm-Roig requested changes

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/actions/Massif.js
> +    delete massifData.id;
C'est pas normal de devoir faire ça. L'API devrait ignorer l'id d'elle-même, plutôt que de vouloir mettre tout le req.body dans la transaction d'update : 

```js 
const updatedMassif = await TMassif.updateOne(massifId).set(req.body);
```

A modifier dans l'API je dirais (je peux faire un déploiement express une fois la modif mergée côté API si tu veux).

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +  defaultMassifValues = massifValues || defaultMassifValues;
Je suis pas trop fan de modifier une `let` qui est en dehors du composant... 
Voir ce que j'ai fait sur le composant `EntranceForm` pour régler ce souci par exemple :slightly_smiling_face:

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/transformers.js
> +  }
Tu peux utiliser `pathOr` ou `propOr` de la librairie ramda pour ce genre de choses.

Tu as des exemples dans les fichiers `transformers.js` de comment les utiliser.

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/pages/Application.jsx
> +        <Route path="/ui/massifs/edit/:massifId" component={MassifEdit} />
`ui/massifs/:massifId/edit `

(cf commentaire que j'ai posté précédemment)

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/pages/EntityEdit/Massif/MassifEditContainer.jsx
> +    padding: 10%;
Il vaut mieux utiliser theme.spacing pour être homogène dans nos paddings et margins à travers toute l'application. Exemple : 

```jsx
const StyledBadge = styled(Badge)`
  margin: ${({ theme }) => theme.spacing(1)}px;
`;
```

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/pages/EntityEdit/Massif/MassifEditContainer.jsx
> +            <Spinner text={' '} size={100} />
Le composant Spinner n'est pas utilisée dans l'application (on devrait le supprimer d'ailleurs), préfère-lui <CircularProgress> de MUI.

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/reducers/GCReducer.js
> +import descriptionPatch from './DescriptionPutReducer';
descriptionPut ici (oui même si c'est le verbe patch, il vaut mieux rester cohérent avec tous les noms des reducers d'edit qui sont nommés "put").

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/reducers/GCReducer.js
> +import namePatch from './NamePutReducer';
namePut

2022-05-16 18:03 UTC, Clm-Roig commented on packages/web-app/src/actions/Description.js
> +  type: POST_DESCRIPTION_FAILURE
POST_DESCRIPTION_SUCCESS

2022-05-17 08:25 UTC, lageta commented on packages/web-app/src/actions/Massif.js
> +    delete massifData.id;
https://github.com/GrottoCenter/Grottocenter3/pull/867

2022-05-17 08:33 UTC, lageta commented on packages/web-app/src/actions/Description.js
> +  type: POST_DESCRIPTION_FAILURE
POST_DESCRIPTION_SUCCESS plutôt ?

2022-05-17 08:34 UTC, Clm-Roig commented on packages/web-app/src/actions/Description.js
> +  type: POST_DESCRIPTION_FAILURE
Oui exact !

2022-05-17 16:24 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +  defaultMassifValues = massifValues || defaultMassifValues;
Alors si c'est à ça que tu fais référence 
![image](https://user-images.githubusercontent.com/74241345/168860918-24a2350d-2f57-411f-bd6d-949673e49950.png)
cela ne marche pas pour moi 🤔

2022-05-17 17:01 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +  defaultMassifValues = massifValues || defaultMassifValues;
Je n'ai pas ton erreur sous les yeux là, je ne peux pas t'aider...
Il n'y a pas que cette ligne qui est impactée, tu dois regarder aussi plus loin et regarder comment s'est utilisé par le composant parent.

2022-05-17 17:07 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/transformers.js
> +  }
Je ne suis pas sûr que l'utilisation de ramda ici simplifie les choses étant donné que l'on manipule des tableaux dans des objets pour le cas du language par exemple je devrai écrire 
`if (data.names){
myObj.language = pathOr('', ['language'], data.names[0])
} `
Comment faire également quand je réalise un traitement sur le résultat de sortie comme avec mon geoJson ?

2022-05-17 17:13 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Massif/transformers.js
> +  }
Rien n'est impossible avec ramda en théorie, notamment grâce à la fonction pipe() qui est extrêmement puissante.  

Ici, sans passer par pipe, tu peux faire : 
```js
language: pathOr('', ['names', 0, 'language'], data),
```

Tu as pleins d'exemples dans les `transformers.js` où on récupère tous les attributs de Grottocenter.

2022-05-17 17:29 UTC, lageta commented on packages/web-app/src/actions/Massif.js
> +    delete massifData.id;
Je ne suis pas sûr de comprendre, tu me dis bien ici que l'id devrait être passé à la fois à l'API dans le path mais aussi dans le body de ma requête ?

2022-05-17 17:33 UTC, Clm-Roig commented on packages/web-app/src/actions/Massif.js
> +    delete massifData.id;
Non je dis juste que tu n'as pas à te soucier du fait d'envoyer des données "en plus" dans ton body. Si j'envoie à l'API : 

PATCH massifs/42
body = {
  toto : 'oui',
  name: 'le massif 42'
}

Le fait qu'y ait toto ou pas n'influe pas du tout le fait que ça va quand même marcher ou échouer. Or là, toi, tu as dû supprimer massifs.id de tes data pour que l'appel à l'API fonctionne. Ça prouve que l'API est sensible au fait que tu lui passes l'id dans le body alors qu'elle devrait l'ignorer. 

L'API ne demande l'id QUE dans l'url.

2022-05-17 17:42 UTC, lageta commented on packages/web-app/src/actions/Massif.js
> +    delete massifData.id;
C'est justement pour éviter d'avoir des paramètres en plus dans la requête et que l'API les signale que j'ai fais une liste de paramètres autorisées. 
Maintenant si ça ne convient pas dans l'api on ne garde que du coup le service getDataFromClient mais ce dernier ne renverra pas d'erreur au client si la requête contient des paramètres non pris en charge par l'API.

Il faut faire l'un ou l'autre je pense mais les deux ne sont pas compatibles.

2022-05-17 17:49 UTC, Clm-Roig commented on packages/web-app/src/actions/Massif.js
> +    delete massifData.id;
> C'est justement pour éviter d'avoir des paramètres en plus dans la requête et que l'API les signale que j'ai fais une liste de paramètres autorisées.

Chose que l'on n'a jamais fait dans Grottocenter, d'où ma remarque qui va dans le sens "boîte noire" pour l'utilisateur. 
Mais pourquoi pas commencer à le faire, oui.

Mais dans ce cas, je veux bien des sources et arguments (best practices / normes en REST) pour choisir la meilleure implémentation et surtout, pour en faire un Service ou un helper réutilisable.

2022-05-17 18:05 UTC, lageta commented on packages/web-app/src/actions/Massif.js
> +    delete massifData.id;
Je suis sûre que ça aurait été très intéressants mais vu que l'on doit rendre nos livrables dans 2 jours je ne pense pas que ça soit judicieux de ma part de m'engager sur un travail de recherche maintenant.😅 Plus tôt ça aurai été avec plaisir par contre ! On va garder ce que vous faites déjà sur Grottocenter.

2022-05-17 18:07 UTC, Clm-Roig commented on packages/web-app/src/actions/Massif.js
> +    delete massifData.id;
C'est un argument totalement recevable ^^

Combiné à cette issue : https://github.com/GrottoCenter/Grottocenter3/issues/717 ça pourrait être un beau travail d'amélioration / refactorisation à l'avenir.

2022-05-17 19:58 UTC, lageta commented on packages/web-app/src/components/appli/EntitiesForm/Massif/index.jsx
> +  defaultMassifValues = massifValues || defaultMassifValues;
J'avais simplement oublié une condition dans un useEffect 👀

2022-05-18 05:20 UTC, Clm-Roig approved these changes

2022-05-19 13:52 UTC, merged