346 massif view
GrottoCenter/grottocenter-front pull request #457
Opened 2022-05-17 14:30 UTC by VivienLvr

fix #346 

Regarder les massifs 580, 581 et 582 pour voir la carte.

2022-05-17 17:18 UTC, Clm-Roig requested changes

2022-05-17 17:18 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Massif/MapMassif.jsx
> +            return (
```js
entrance.latitude && entrance.longitude && ( <Marker...> ) 
```

ne fonctionne pas ici ?

2022-05-17 17:18 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +                {massif.descriptions[0] ? (
Pourquoi n'utiliser que la première description ? 
Tu as un composant Descriptions dans Entrance, tu peux le copier / coller dans Massif (un jour je refactoriserai tout ça proprement en dehors des dossiers).

2022-05-17 17:18 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +                    {formatMessage({ id: 'No description for this massif' })}
Ce n'est pas le message d'erreur que l'on utilise habituellement (cf les messages d'erreur que tu as mis plus bas qui sont, eux, au bon format).

2022-05-17 20:06 UTC, VivienLvr commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +                {massif.descriptions[0] ? (
Je peux l'importer depuis le dossier Entry ou je le copie dans le dossier Massif ?

2022-05-17 20:06 UTC, VivienLvr commented on packages/web-app/src/components/appli/Massif/MapMassif.jsx
> +            return (
Si, c'est modifié.

2022-05-17 20:33 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +                {massif.descriptions[0] ? (
Si tu peux l'utiliser tel quel, importe le. C'est pas dit que ça marche à cause des context / provider.
Sinon copie / colle.

2022-05-17 20:34 UTC, VivienLvr commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +                {massif.descriptions[0] ? (
Ça fait une Card dans une Card, c'est pas grave ?

<img width="1208" alt="Capture d’écran 2022-05-17 à 22 33 28" src="https://user-images.githubusercontent.com/30286062/168905060-b98936b5-93ce-4303-aa0b-6b95bb2976af.png">

2022-05-17 20:36 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +                {massif.descriptions[0] ? (
On va éviter oui. 
Copie colle et enlève tout ce qui ScrollableContent / Layout.

2022-05-17 20:56 UTC, VivienLvr commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +                {massif.descriptions[0] ? (
Au passage, je crois qu'il y a un soucis avec l'affichage de l'auteur, c'est un booléen qui est affiché. J'ai corrigé l'erreur dans mon fichier.
<img width="342" alt="Capture d’écran 2022-05-17 à 22 55 36" src="https://user-images.githubusercontent.com/30286062/168908623-a9403722-ad6f-472c-af69-b8fb1a0b673a.png">

2022-05-22 21:03 UTC, Clm-Roig requested changes

2022-05-22 21:03 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +                      id: 'This massif does not have a description'
'This massif has no description listed yet.' (histoire d'être homogène avec les autres messages)

Aussi, il manque un point à la fin.

2022-05-22 21:03 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Massif/Massif.jsx
> +};
Je crois que c'est inutile. 
Si tu supprimes ces 3 lignes, par défaut, ce sera undefined vu qu'il n'y aura pas de "defaultProps". A tester.

2022-05-22 21:03 UTC, Clm-Roig commented on packages/web-app/src/lang/en.json
> +  "This massif does not have a description": "This massif does not have a description",
Message à harmoniser (cf précédent commentaire)

2022-05-23 13:30 UTC, Clm-Roig commented
J'ai juste force push pour mettre un "s" au message "no description listed yet". C'est tout bon sinon !

2022-05-23 13:30 UTC, Clm-Roig approved these changes

2022-05-23 13:50 UTC, urien commented
Le système d'association des entrées au périmètre du massif ne semble pas fonctionner.
Je n'ai aucune entrée associée au massif du mont César alors qu'il devrait y en avoir
![image](https://user-images.githubusercontent.com/1165144/169834428-15f05439-3acc-4560-82ca-8d48da01e59b.png)

2022-05-23 13:51 UTC, urien commented
![image](https://user-images.githubusercontent.com/1165144/169834559-28270eed-16bc-4883-8a0a-b10dadf06a2a.png)

2022-05-23 13:52 UTC, Clm-Roig commented
Je crois que c'est cette PR (non-mergée) de l'API qui s'occupe de ça : https://github.com/GrottoCenter/Grottocenter3/pull/831 
Va falloir donc la merger et la déployer avant que ça ne fonctionne ici 🙂 

@VivienLvr il faudra donc attendre que la PR du back soit mergée avant de merger ici, attention à ne pas déployer en prod le client sans le back.

2022-05-23 13:53 UTC, Clm-Roig commented
J'en profite pour demander une (petite) modification : 
![Uploading image.png…]()

Le troisième texte est en italique, pas les autres.

2022-05-23 14:00 UTC, urien commented
Ce serait bien de rajouter le bouton d'édition ;-)

2022-05-23 14:02 UTC, VivienLvr commented
Le bouton d'édition ne s'affiche que lorsqu'on est connecté normalement.

2022-05-23 14:05 UTC, urien commented
Oui ! Bien sûr ! cela fonctionne, c'est parfait

2022-05-30 12:41 UTC, merged