342 person edit
GrottoCenter/grottocenter-front pull request #458
Opened 2022-05-17 21:47 UTC by jodiecottave

fix #342
Attention cette pull request nécessite la modification de l'API concernant le changement de mot de passe.

2022-05-18 05:21 UTC, Clm-Roig commented
> ## warning Attention cette pull request nécessite la modification de l'API concernant le changement de mot de passe.

C'est pas encore PR si je ne me trompe pas ?

2022-05-18 05:32 UTC, Clm-Roig requested changes

2022-05-18 05:32 UTC, Clm-Roig commented on packages/web-app/src/actions/User.js
> +            makeErrorMessage(error.message, `Fetching user id ${userId}`)
Quelle est la différence avec `actions/Person/fetchUser()` ? On a 2 fichiers ici qui me paraissent équivalents ici (Person et User).

2022-05-18 05:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEdit/index.jsx
> +  `;
Je ne sais plus si c'est à toi que j'ai fait la remarque, mais 3 choses : 
- tout ce qui peut être sorti du composant et mis avant dans le fichier doit l'être.
- on évite les valeurs hardcodées pour les padding et margin en leur préférent `theme.spacing`
- en quoi mettre un padding à 10% fait qu'un div est centré ? Je trouve le nom (ou la solution) pas cohérent(e).

2022-05-18 05:32 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEdit/index.jsx
> +            <Spinner text={' '} size={100} />
Le Spinner est déprécié, il n'est utilisé nulle part dans l'application (je vais bientôt le supprimer). Préfère-lui le CircularProgress de MUI.

2022-05-18 05:32 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/PersonForm.jsx
> +  `;
à sortir du composant

2022-05-18 05:32 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +  // const forgotPasswordState = useSelector(state => state.forgotPassword);
Reliquat à supprimer ?

2022-05-18 05:32 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +import MakeUserData from './transformer';
Sans majuscule, il s'agit d'une méthode.

2022-05-18 05:32 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +                    id: 'An error occurred when updating a user!'
"the user"

2022-05-18 05:32 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +                          style={{ margin: '8px', marginLeft: 'auto' }}
Pas de margin hardcodé, préfère theme.spacing dans un styled component.

2022-05-22 21:00 UTC, Clm-Roig requested changes

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEdit/index.jsx
> +const Center = styled(Typography)`
Pas besoin d'utiliser un Typography ici, tu peux te contenter d'un div. 
Ou mieux, directement dans le render : 
 ```js
<Box display="flex" alignItems="center" justifyContent="center">

</Box>
```

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEdit/index.jsx
> +  }
En mettant des return dans les `if / return`, tu ne bénéficies pas du Layout : ça casse l'esthétique de la page... 

Le code du content de Layout est pas trop touffu, tu peux te permettre d'y mettre de la logique dedans 🙂

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/Application.jsx
> +        <Route path="/ui/persons/:personId/edit" component={PersonEdit} />
A descendre 2 lignes plus bas pour mettre toutes les routes /persons côte à côte

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/PersonForm.jsx
> +  };
Pour des vérifications simples, react-hook-form intègre des "rules" de validation toutes prêts : 
List of validation rules supported:
  -  required
 -   min
  -  max
   - minLength
  -  maxLength
 -   pattern
-    validate

https://react-hook-form.com/get-started/#applyvalidation

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/PersonForm.jsx
> +  control: PropTypes.shape({}),
`control: PropTypes.shape({}).isRequired,` --> sans ça le composant ne fonctionne pas, d'où le "isRequired"

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/PersonForm.jsx
> +  watch: PropTypes.shape({})
isRequired

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +const useStyles = makeStyles(theme => ({
On n'utilise jamais makeStyles dans Grottocenter (pur choix arbitraire). On lui préfère styled() plutôt 🙂

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +        'user.passwordConfirmation'
'user.passwordConfirmation' est en double.

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +      footer=""
Le footer est facultatif dans le Layout, tu peux supprimer l'attribut si tu ne t'en sers pas.

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +              <form>
Pourquoi ce form ? Je pense que tu peux le supprimer.

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +              <form>
Pareil, form pas utile.

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +                      All steps completed - you&apos;re finished
A traduire en utilisant "formatMessage". 

"You're finished" je ne crois pas que ça se dise en anglais, ou en tout cas, pas dans ce sens-là 😅

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +    id: PropTypes.number,
L'id est ".isRequired"

2022-05-22 21:00 UTC, Clm-Roig commented on packages/web-app/src/reducers/GCReducer.js
> +
Sauts de ligne à supprimer + ordre alphabétique (à mettre après updateLocation)

2022-05-23 13:38 UTC, Clm-Roig requested changes
Quelques détails très rapides à corriger, sinon le code est bon ! Je teste la fonctionnalité de suite.

2022-05-23 13:38 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +  marginbottom: theme.spacing(1);
Il manque le tiret dans le nom de la propriété CSS

2022-05-23 13:38 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +  marginright: theme.spacing(1);
il manque le tiret

2022-05-23 13:56 UTC, urien commented
Actuellement le bouton pour éditer son profil n'est pas actif
Quand on édit son profil le message d'attente est undefined undefined.
Je ne fais pas de test sur le changement de mel et de mot de passe, je crois qu'il faut que la partie back soit validée

2022-05-23 14:03 UTC, Clm-Roig commented
Tu peux y accéder en ajoutant /edit à la fin de l'url de ton profil @urien. Mais effectivement, on devrait pouvoir le faire via l'icône d'édition en haut à droite. 

- Dans mon récap, rien n'est affiché si jamais je fais "Next" sans rien avoir touché : 
![image](https://user-images.githubusercontent.com/20704943/169836635-9b9a8a30-924e-45c6-a1aa-454a946f682d.png)
J'ai cru à un bug. L'idéal serait de verrouiller le "Next" tant qu'on n'a pas touché à au moins un champ.

- L'empilement de 3 "cartes" pique les yeux. Normalement on évite d'empiler ne serait-ce qu'une carte sur une autre.
![image](https://user-images.githubusercontent.com/20704943/169836921-d688b0ff-09ec-4e88-a1ca-932bf70bf353.png)

La police est un peu grosse pour les attributs que l'on modifie aussi.

Ça aurait été bien d'avoir l'ancienne valeur à côté de la nouvelle avant de soumettre les modifs mais je pinaille.

2022-05-24 06:18 UTC, urien commented
Pour un utilisateur le changement de mot de passe ne fonctionne pas : à la validation on a un message rouge qui apparait rapidement mais on passe à la fenêtre de validation. La validation se passe bien mais le mot de passe n'a pas été changé

2022-05-24 06:21 UTC, urien commented
On a une étape pour vérifier la véracité des informations puis une étape supplémentaire pour finir : cela fait une étape de trop

2022-05-24 06:24 UTC, urien commented
Le changement de mel se déroule bien

2022-05-24 06:25 UTC, urien commented
Comme administrateur si je change le mel d'un utilisateur la procédure se déroule normalement mais le mail n'est pas changé

2022-05-24 07:56 UTC, Clm-Roig requested changes
Il y a un souci dans l'architecture des fichiers : 
- `common/PersonEdit/index.js` devrait être dans `appli/PersonEdit.index.js`
- Tu as inversé le contenu de `/pages` avec `/components`. Normalement c'est la page qui importe des composants. Ici c'est l'inverse, PersonEdit importe PersonEditPage.

2022-05-24 07:56 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/Summary.jsx
> +  );
Pourquoi avoir tout débouncé ?

2022-05-24 07:56 UTC, Clm-Roig commented on packages/web-app/src/pages/PersonEditPage/index.jsx
> +    if (result && isChanged()) {
Mon précédent commentaire te demander de désactiver le bouton Next tant que le formulaire n'avait pas été modifié. Ici, on peut toujours cliquer sur le bouton mais il ne se passe rien à cause de ce isChanged().

isChanged() est de trop ici, il faut l'utiliser directement sur le disabled du bouton "Next".

2022-05-26 04:26 UTC, urien commented
Merci @jodiecottave pour le travail réalisé. Je refais des tests
Le changement de mot de passe se déroule bien pour un utilisateur. 
Comme administrateur j'arrive à changer nom, prénom et pseudo d'un utilisateur.

Zut : le changement de mel et de mot de passe d'un utilisateur, par l'adminstrateur ne fonctionnent pas
Est ce que vous auriez le temps de reprendre l'affichage des boutons ?
![image](https://user-images.githubusercontent.com/1165144/170415871-d3943455-5282-46ef-9f90-5f7b957e4975.png)

2022-05-26 17:21 UTC, jodiecottave commented
> 

Bonjour @urien , il me semblait justement que nous avions décidé que seul l’utilisateur pouvait changer son mail et son mot de passe, ce n’est plus le cas ? 
Et oui bien sûr je peux les reprendre, comment voulez-vous les afficher ?

2022-05-26 18:05 UTC, urien commented
Ce serait super @jodiecottave .
En tant qu'administrateur j'ai exactement le même affichage que les utilisateurs. 
Il suffirait que la modification du mot de passe et du mel d'un utilisateur, par un administrateur fonctionne.
Cela permettrait de "sauver" des utilisateurs qui n'ont plus la main sur une vieille adresse mel ou pour fournir un mot de passe valide si le service d'envoi de mel ne fonctionnait plus. Si c'est trop long il faut laisser ainsi, je préviendrai les administrateurs

2022-05-27 10:16 UTC, jodiecottave commented
> 

Je pense que cela demande beaucoup de modifications au niveau du back qui demandera un certain temps car je crois que l'on ne peut pour l'instant pas modifier ou simplement avoir accès à l'adresse email et au mot de passe d'un utilisateur sans être cet utilisateur, ou peut être je suis passée à coté d'une manière simple de récupérer le token d'un utilisateur sans être connecté @Clm-Roig ? 
Je peux cependant bloquer ou cacher les champs de saisie liés à la modification de mail et mot de passe pour l'administrateur, cela pourrait être une alternative pour le moment.

2022-05-27 10:23 UTC, urien commented
Merci, c'est une solution qui me convient parfaitement

2022-05-27 14:05 UTC, Clm-Roig commented
> > 
> 
> Je pense que cela demande beaucoup de modifications au niveau du back qui demandera un certain temps car je crois que l'on ne peut pour l'instant pas modifier ou simplement avoir accès à l'adresse email et au mot de passe d'un utilisateur sans être cet utilisateur, ou peut être je suis passée à coté d'une manière simple de récupérer le token d'un utilisateur sans être connecté @Clm-Roig ? Je peux cependant bloquer ou cacher les champs de saisie liés à la modification de mail et mot de passe pour l'administrateur, cela pourrait être une alternative pour le moment.

Si la route n'inclut pas l'id de l'utilisateur que l'on souhaite modifier, c'est en effet impossible (et il me semble que c'est le cas ici). 

Ouvrons une issue pour cette amélioration et ça ira pour le moment je pense 🙂

2022-05-29 18:50 UTC, urien commented
J'ai l'impression que cela ne change rien quand on est administrateur, car les administrateurs sont aussi user.
Je propose de publier ce travail qui fonctionne très bien.
Merci

2022-05-31 08:52 UTC, Clm-Roig requested changes

2022-05-31 08:52 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEditPage/Summary.jsx
> +  );
Même commentaire que la dernière fois : pourquoi ce debounce ?

2022-05-31 09:16 UTC, Clm-Roig commented
![image](https://user-images.githubusercontent.com/20704943/171138961-9dc41700-aaaf-47c1-bd46-70ea373c0e5e.png)
Toujours un petit souci sur les boutons d'action en bas. Niveau css, ne réinvente pas la roue : on a des formulaires un peu partout avec les mêmes boutons. Tu peux t'en inspirer.

2022-05-31 09:23 UTC, Clm-Roig requested changes

2022-05-31 09:23 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEditPage/PersonForm.jsx
> +        id: 'Invalid email or password.'
Le message est à revoir. Ici ce n'est pas que le mot de passe est invalide, c'est qu'il est trop court.

2022-05-31 09:23 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEditPage/PersonForm.jsx
> +          id: 'Invalid email or password.'
"Invalid email" tout court ici.

2022-05-31 09:23 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEditPage/index.jsx
> +                        disabled={!isDirty}
Le isDirty ne fonctionne pas correctement. Selon [la doc](https://react-hook-form.com/api/usecontroller/controller/), il se base sur les defaultValues pour éviter d'être dirty même si on re-rentre la même valeur.
Or, si je change mon prénom "Clément" par "Clément", j'ai quand même accès au bouton "Next".

2022-05-31 09:24 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEditPage/index.jsx
> +                        disabled={!isDirty}
Voir cette discussion éventuellement : https://github.com/react-hook-form/react-hook-form/issues/3562

2022-05-31 09:58 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEditPage/index.jsx
> +                        disabled={!isDirty}
Le isDirty a l'air buggué avec des defaultValues. Tu peux, le cas échéant, utiliser dirtyFields et vérifier qu'il vaut bien un objet vide `{ }`

2022-06-06 09:26 UTC, Clm-Roig commented
@jodiecottave du nouveau quant à mes dernières demandes de changement ? Tu veux retravailler sur cette PR ou on prend le relai ?

2022-06-09 12:41 UTC, urien commented
Comme utilisateur j'ai essayé de mettre à jour mon pseudo, mon nom, mon prénom, le processus se passe bien mais à la fin la mise à jour n'apparait pas.
De même si je souhaite apporter des modifications au profil d'un utilisateur depuis un compte administrateur

2022-07-20 08:55 UTC, Clm-Roig commented
@urien si j'ai du temps dans les semaines à venir, je pensais terminer cette Pull Request. J'imagine que Jodie n'y touchera plus :sweat_smile:

2022-07-20 08:56 UTC, urien commented
Ce serait très sympa

2022-07-20 13:32 UTC, urien commented
Je viens de faire un test comme utilisateur
Les changements de nom, prénom et nickname ne sont pas pris en compte. Le changement de mot de passe fait que ni l'ancien ni le nouveau ne fonctionne. Par contre la récupération via mel est OK !

2022-08-05 09:28 UTC, urien approved these changes
Cela marche très bien, pour tous les champs en tant qu'utilisateur
Et en tant qu'administrateur sur les champs nom, prénom et surnom. Comme les champs mdp et mail ne sont plus visibles il n'y aura pas d'erreur
Merci beaucoup

2022-08-05 09:30 UTC, Clm-Roig approved these changes

2022-08-05 09:30 UTC, Clm-Roig commented on packages/web-app/src/components/common/PersonEditPage/index.jsx
> +                        disabled={!isDirty}
C'est bon j'ai réglé le souci. Les userValues contenaient bien trop de valeurs comparé au formulaire. Il fallait supprimer toutes les propriétés qui n'étaient pas utilisé par le formulaire. Je pousse le correctif :slightly_smiling_face:

2022-08-05 09:31 UTC, merged