feat(#404): edit and create entrance history
GrottoCenter/grottocenter-front pull request #493
Opened 2022-06-05 22:52 UTC by bsoufflet

WARNING : API routes do not exist yet to create/edit an history...

J'ai pour l'instant fait un ensemble de copier/coller de ce qui avait été fait pour "location". Il faudrait j'imagine un jour ou l'autre faire un refactoring car le create/edit d'une location, history, comment, ... se ressemble beaucoup. Cependant ce n'est pas non plus identique (gestion de is_sensitive, pas de title, ...) et le refactoring demanderait tout de meme du temps.
En pesant le pour et le contre j'ai l'impression qu'il est plus urgent de proposer rapidement ces features d'edit / create pour les données encyclopédiques meme si il y a un peu de copie de code :(

![image](https://user-images.githubusercontent.com/985903/172073824-f7ee9c2e-0614-42e1-8e00-6c01c6b7ff72.png)

2022-06-06 09:32 UTC, Clm-Roig requested changes
Tu n'as pas fait de reducers, c'est voulu ? 

Concernant les duplications, oui va falloir faire quelque chose, ça s'accumule... J'ai créé #459 pour lister ce qui pouvait être refactorisé ensemble.

2022-06-06 09:32 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Histories/index.jsx
> +                id: 'There is currently no history for this entrance.'
Chaîne de traduction à ajouter au fichier en.json

2022-06-06 17:08 UTC, urien commented
J'ai créé un historique qui n'a pas été enregistré

2022-06-06 18:00 UTC, Clm-Roig commented
> J'ai créé un historique qui n'a pas été enregistré

> WARNING : API routes do not exist yet to create/edit an history...

Le serveur n'est pas prêt encore pour recevoir la requête de création / update d'history apparemment.

2022-06-07 22:59 UTC, bsoufflet commented
> Tu n'as pas fait de reducers, c'est voulu ?
> 
> Concernant les duplications, oui va falloir faire quelque chose, ça s'accumule... J'ai créé #459 pour lister ce qui pouvait être refactorisé ensemble.

C'est bon normalement @Clm-Roig :)
Je viens de push pas mal de changements que j'avais oublié dans mon premier commit pour HISTORY et j'ai aussi ajouté DESCRIPTION

2022-06-07 23:00 UTC, bsoufflet commented
@Clm-Roig : je ne trouve pas dans le back pour la route GET d'une entrance pourquoi la property "language" retourne un string dans le cas de "descriptions" ou "histories" et un object das le cas de "locations"... Une idée ? Cela me bloque pour avoir un edit qui fonctionne bien...

2022-06-08 16:07 UTC, urien commented
La description fonctionne super bien. Pour l'historique il doit encore manquer encore quelque chose côté back

2022-06-26 14:35 UTC, urien approved these changes

2022-06-29 22:58 UTC, bsoufflet commented
@Clm-Roig : Ca te semble bon ?

2022-06-30 08:07 UTC, Clm-Roig approved these changes

2022-06-30 08:07 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Provider.js
> +  }).isRequired,
Ce todo va rester là ou il va être réglé quand l'API va être poussée en prod ?

2022-06-30 08:07 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Provider.js
> +  }).isRequired,
Pareil que le précédent commentiare sur le todo

2022-07-15 22:49 UTC, merged