WIP Create entrance
GrottoCenter/grottocenter-front pull request #56
Opened 2021-10-31 15:04 UTC by maximenathan

Resolve https://github.com/GrottoCenter/grottocenter-front/issues/40

2021-11-22 22:43 UTC, bsoufflet approved these changes
C'est une première version simple mais efficace.

@urien : Il faut maintenant prévoir des petits tickets dans Github pour améliorer cette page : 
- sélection de la position en déplaçant le curseur sur la carte (avec fond satellite)
- récupération auto de l'adresse, pays, ... via l'API de Google
- récupération auto de la langue du nom de l'entrée en utilisant la langue actuelle de Grottocenter
- création de la cave dans la première étape si elle n'existe pas encore
- convertisseur de coordonnées accessible ici 
- affichage de certains champs optionnels manquant comme la qualité des coordonnées, ...
- 
@Clm-Roig : 
- Il semble que Maxime avait du mal à faire un POST avec direct l'ID de passé. Par exemple `cave:12345` au lieu de `cave:{id:12345}`...
- ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?

2021-11-22 23:07 UTC, bsoufflet commented
@maximenathan : Il y avait 2 environnements de test Azure inutile (qui dataient de tous les PR transifex) que j'ai supprimé afin que cette PR soit testable en ligne avant le merge ;) @urien @Clm-Roig A vos tests ;)

2021-11-23 06:58 UTC, urien commented
C'est peut être volontaire mais la validation n'aboutit pas pour moi.
Invalid request - Bad request: 
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.grottocenter.org/api/v1/entrances/75227. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.

C'est vraiment bien comme organisation

2021-11-23 09:05 UTC, Clm-Roig commented
> @Clm-Roig :
> 
>     * Il semble que Maxime avait du mal à faire un POST avec direct l'ID de passé. Par exemple `cave:12345` au lieu de `cave:{id:12345}`...
> 

Oui c'est parce que ce n'est pas encore déployé en production. Je déploie une nouvelle version ce matin, tout devrait fonctionner après ça !

2021-11-23 09:38 UTC, Clm-Roig commented
>     * ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?

Je confirme, ce sont des paramètres de cave côté API. Ces informations sont ignorées par l'API pour le moment vu que je ne fait que créer une entrance sans toucher à sa cave.

2021-11-23 09:49 UTC, bsoufflet commented
> > ```
> > * ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?
> > ```
> 
> Je confirme, ce sont des paramètres de cave côté API. Ces informations sont ignorées par l'API pour le moment vu que je ne fait que créer une entrance sans toucher à sa cave.

@maximenathan : Le mieux est peut-être de ne pas afficher ces champs pour l'instant du coup.
@urien : L'idéal serait d'afficher plus tard ces champs spécifiques au réseau uniquement si l'utilisateur ne sélectionne pas de réseau à la première étape (sinon ces champs pourraient devenir "read only" juste pour confirmer que l'on a choisi le bon réseau et pas un homonyme...)

2021-11-23 09:50 UTC, bsoufflet commented
> > ```
> > * ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?
> > ```
> 
> Je confirme, ce sont des paramètres de cave côté API. Ces informations sont ignorées par l'API pour le moment vu que je ne fait que créer une entrance sans toucher à sa cave.

@maximenathan : Tu voudras repasser sur l'objet plus simple après (sans le `id:`) ?

2021-11-23 10:29 UTC, Clm-Roig requested changes
Il faudrait ajouter toutes les nouvelles clés de traduction au fichier `en.json`, je peux m'en charger @maximenathan si tu le souhaites.

2021-11-23 10:29 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/Details.jsx
> +              <Translate>The cavity is does contain water</Translate>
`The cavity contains water` plutôt non ? Ou `Does the cavity contain water?` avec le point d'interrogation.

2021-11-23 10:29 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/index.jsx
> +  // TODO set country from position
Ces 2 TODOs sont faits non ?

2021-11-23 10:29 UTC, Clm-Roig commented on packages/web-app/src/features/QuickSearch.jsx
>    searchOnTypes = ['documents', 'entrances', 'grottos', 'massifs'],
On peut rajouter le type "caves" ici

2021-11-23 10:29 UTC, Clm-Roig commented on packages/web-app/src/pages/EntityCreation/index.jsx
> +                  id: 'You must be authenticated to submit a new entity'
Ajouter un point à la fin ?

2021-11-25 22:30 UTC, maximenathan commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/index.jsx
> +  // TODO set country from position
Non malheureusement
Country rien n'est automatique. C'est un select avec par défaut France
Latitude/longitude c'est par rapport à la position de l'utilisateur (si possible)

2021-11-25 22:34 UTC, maximenathan commented
> > > ```
> > > * ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?
> > > ```
> > 
> > 
> > Je confirme, ce sont des paramètres de cave côté API. Ces informations sont ignorées par l'API pour le moment vu que je ne fait que créer une entrance sans toucher à sa cave.
> 
> @maximenathan : Le mieux est peut-être de ne pas afficher ces champs pour l'instant du coup. @urien : L'idéal serait d'afficher plus tard ces champs spécifiques au réseau uniquement si l'utilisateur ne sélectionne pas de réseau à la première étape (sinon ces champs pourraient devenir "read only" juste pour confirmer que l'on a choisi le bon réseau et pas un homonyme...)

Donc on n'affiche pas la 3 ème (dernière) étape du formulaire ?

2021-11-25 22:42 UTC, bsoufflet commented
> > > > ```
> > > > * ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?
> > > > ```
> > > 
> > > 
> > > Je confirme, ce sont des paramètres de cave côté API. Ces informations sont ignorées par l'API pour le moment vu que je ne fait que créer une entrance sans toucher à sa cave.
> > 
> > 
> > @maximenathan : Le mieux est peut-être de ne pas afficher ces champs pour l'instant du coup. @urien : L'idéal serait d'afficher plus tard ces champs spécifiques au réseau uniquement si l'utilisateur ne sélectionne pas de réseau à la première étape (sinon ces champs pourraient devenir "read only" juste pour confirmer que l'on a choisi le bon réseau et pas un homonyme...)
> 
> Donc on n'affiche pas la 3 ème (dernière) étape du formulaire ?

Oui, on affichera ces 3 champs uniquement lorsque l'on pourra créer un réseau au moment de la création d'une entrée. EN attendant je mettrai potentiellement ces champs en "read only" dans la section "cave / réseau" et je les remplirai avec les informations provenant de la cave sélectionnée. (si c'est pas trop long à faire ;)

2021-11-26 06:54 UTC, urien commented
En fait dans la situation de base (c'est supérieur à 999 sur 1000) on créé une entrée et une nouvelle cavité. 
Un fonctionnement plus simple pour les utilisateurs serait de sauter l'étape 1 et de créer automatiquement une nouvelle cavité pour chaque création d'entrée avec uniquement les étapes 2 et 3.
Ensuite lorsqu'on sera sur la création d'un réseau (une cavité associée à plusieurs entrées) il faudra faire ce que tu fais à l'étape 1 c'est a dire choisir obligatoirement une entrée parmi celles qui existent et donner un nom a cette nouvelle cavité (qui correspond à un réseau) mais pas les étapes 2 et 3. Un réseau n'a pas de coordonnées, seulement la moyenne des coordonnées des cavités/entrées qui le compose

2021-11-28 11:07 UTC, maximenathan commented
> > > > > ```
> > > > > * ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?
> > > > > ```
> > > > 
> > > > 
> > > > Je confirme, ce sont des paramètres de cave côté API. Ces informations sont ignorées par l'API pour le moment vu que je ne fait que créer une entrance sans toucher à sa cave.
> > > 
> > > 
> > > @maximenathan : Le mieux est peut-être de ne pas afficher ces champs pour l'instant du coup. @urien : L'idéal serait d'afficher plus tard ces champs spécifiques au réseau uniquement si l'utilisateur ne sélectionne pas de réseau à la première étape (sinon ces champs pourraient devenir "read only" juste pour confirmer que l'on a choisi le bon réseau et pas un homonyme...)
> > 
> > 
> > Donc on n'affiche pas la 3 ème (dernière) étape du formulaire ?
> 
> Oui, on affichera ces 3 champs uniquement lorsque l'on pourra créer un réseau au moment de la création d'une entrée. EN attendant je mettrai potentiellement ces champs en "read only" dans la section "cave / réseau" et je les remplirai avec les informations provenant de la cave sélectionnée. (si c'est pas trop long à faire ;)

La section est maintenant en `readonly`, et si possible remplis avec les info de la cave sélectionnée

2021-11-28 16:09 UTC, urien commented
C'est parfait

2021-11-28 23:27 UTC, bsoufflet commented
> > > > > > ```
> > > > > > * ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Je confirme, ce sont des paramètres de cave côté API. Ces informations sont ignorées par l'API pour le moment vu que je ne fait que créer une entrance sans toucher à sa cave.
> > > > 
> > > > 
> > > > @maximenathan : Le mieux est peut-être de ne pas afficher ces champs pour l'instant du coup. @urien : L'idéal serait d'afficher plus tard ces champs spécifiques au réseau uniquement si l'utilisateur ne sélectionne pas de réseau à la première étape (sinon ces champs pourraient devenir "read only" juste pour confirmer que l'on a choisi le bon réseau et pas un homonyme...)
> > > 
> > > 
> > > Donc on n'affiche pas la 3 ème (dernière) étape du formulaire ?
> > 
> > 
> > Oui, on affichera ces 3 champs uniquement lorsque l'on pourra créer un réseau au moment de la création d'une entrée. EN attendant je mettrai potentiellement ces champs en "read only" dans la section "cave / réseau" et je les remplirai avec les informations provenant de la cave sélectionnée. (si c'est pas trop long à faire ;)
> 
> @bsoufflet La section est maintenant en `readonly`, et si possible remplis avec les info de la cave sélectionnée

Ce ne serait pas mieux de mettre les champs "read only" de la section 3 dans la section 1 "cave" pour voir immédiatement les propriété de la "Cave" que tu viens de sélectionner ?
comme cela plus tard lorsque l'on pourra créer la cave associé à l'entrée il suffira de rajouter un champ "name" et de rendre éditable ces champs de la section 3.
Vous en pensez quoi @maximenathan @urien ?

2021-11-29 05:02 UTC, urien commented
Tu as raison Benjamin, ce serait mieux.
En fait quand on créé une entrée et une cavité en même temps elles ont le
même nom. Il n'y aura pas besoin d'ajouter un champ

Le lun. 29 nov. 2021 à 00:27, Benjamin ***@***.***> a écrit :

> * ca fonctionne bien d'envoyer les parametres depth, (3ᵉ section du formulaire)... avec l'entrance ? Ca va mettre à jour la cave ? Dans ce cas là il faudrait préremplir ces champs avec les propriété de la cave ? Si l'utilisateur les changes ou met des données vide cela va supprimer les valeurs sur la cave ?
>
>
> Je confirme, ce sont des paramètres de cave côté API. Ces informations
> sont ignorées par l'API pour le moment vu que je ne fait que créer une
> entrance sans toucher à sa cave.
>
> @maximenathan <https://github.com/maximenathan> : Le mieux est peut-être
> de ne pas afficher ces champs pour l'instant du coup. @urien
> <https://github.com/urien> : L'idéal serait d'afficher plus tard ces
> champs spécifiques au réseau uniquement si l'utilisateur ne sélectionne pas
> de réseau à la première étape (sinon ces champs pourraient devenir "read
> only" juste pour confirmer que l'on a choisi le bon réseau et pas un
> homonyme...)
>
> Donc on n'affiche pas la 3 ème (dernière) étape du formulaire ?
>
> Oui, on affichera ces 3 champs uniquement lorsque l'on pourra créer un
> réseau au moment de la création d'une entrée. EN attendant je mettrai
> potentiellement ces champs en "read only" dans la section "cave / réseau"
> et je les remplirai avec les informations provenant de la cave
> sélectionnée. (si c'est pas trop long à faire ;)
>
> @bsoufflet <https://github.com/bsoufflet> La section est maintenant en
> readonly, et si possible remplis avec les info de la cave sélectionnée
>
> Ce ne serait pas mieux de mettre les champs "read only" de la section 3
> dans la section 1 "cave" pour voir immédiatement les propriété de la "Cave"
> que tu viens de sélectionner ?
> comme cela plus tard lorsque l'on pourra créer la cave associé à l'entrée
> il suffira de rajouter un champ "name" et de rendre éditable ces champs de
> la section 3.
> Vous en pensez quoi @maximenathan <https://github.com/maximenathan> @urien
> <https://github.com/urien> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrottoCenter/grottocenter-front/pull/56#issuecomment-981173428>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAI4OWDF6GDNPQ6HYLTVGXDUOK3GNANCNFSM5HCMIVNA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2022-01-09 14:33 UTC, maximenathan commented
Merge de la création d'une Entrée & Cavité en une seul étape 
https://docs.google.com/document/d/1bpM3sL7zbfY5eG2zatdAt4mp5PFtmQJBKnu3rF3KtMo/edit

@urien @bsoufflet  wdyt ?

2022-01-09 14:49 UTC, urien commented
Super, cela avance bien
Quelques propositions
quand on créé une cavité qui n'est pas reliée à un réseau le nom de l'entrée est le nom de la cavité.  à l'étape deux il faudrait remettre le nom mis à l'étape un et qu'il ne soit pas éditable (de meme pour la langue). Ou ne pas l'afficher (ni la langue)
la géolocalisation c'est super !
Tu as mis la possibilité de mettre une description, c'est super. Est ce que tu pourrais mettre aussi la même chose pour location ? Cela permettrait d'inciter les contributeurs de mettre ces deux infos qui sont essentielles, au moment où ils crééent une cavité

2022-01-09 15:06 UTC, urien commented
La partie association d'une entrée à une cavité existante marche très bien

2022-01-10 09:26 UTC, Clm-Roig requested changes
Si je ne me trompe pas, lors que l'on "like to a network", les textes et la recherche rapide doivent se faire sur les networks. 

Il manque aussi les traductions dans en.json, je peux m'en occuper si tu veux Maxime (?).

Je lance le code sur ma machine tout de suite et je te fais un retour.

2022-01-10 09:26 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/Cave/CaveSelection.jsx
> +const getCaveToString = massif => {
`getCaveToString = cave => cave.name` plutôt non ?

2022-01-10 09:26 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/Cave/CaveSelection.jsx
> +      resourceType: 'caves'
`resourceType: 'networks'` ici. Une entrée se rattache à un network, ceux-ci étant bien disponibles dans la quicksearch. Il faudrait renommer tout le composant d'ailleurs.

2022-01-10 09:26 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/Cave/CaveSelection.jsx
> +            id: 'An entrance must be attached to an existing cave'
`... to an existing network.`

2022-01-10 09:26 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/Cave/index.jsx
> +        {/* <FormHelperText>{helperText}</FormHelperText> */}
à supprimer ?

2022-01-10 09:26 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/Details.jsx
> +      return formatMessage({ id: 'Distance must be superior or equal 0' });
`... or equal to 0`

2022-01-10 09:26 UTC, Clm-Roig commented on packages/web-app/src/features/QuickSearch.jsx
> +  searchOnTypes = ['documents', 'entrances', 'grottos', 'massifs', 'caves'],
Ajouter `'networks'` dans les types possibles

2022-01-10 09:26 UTC, Clm-Roig commented on packages/web-app/src/features/QuickSearch.jsx
> +    'documents',
`'networks'` (cf précédent commentaire)

2022-01-10 09:28 UTC, Clm-Roig commented on packages/web-app/src/pages/EntityCreation/CreationForm.jsx
> +        <Translate>Entrance, cave, ...</Translate>
Il y a une virgule de trop après `cave`

2022-01-10 10:03 UTC, Clm-Roig commented on packages/web-app/src/pages/EntityCreation/CreationForm.jsx
> +  entity: PropTypes.oneOfType(values(ENTITY)).isRequired,
`PropTypes.oneOf` (au lieu de `oneOfType`) => c'est une énumération de valeurs, pas de types.

2022-01-10 10:07 UTC, Clm-Roig commented on packages/web-app/src/components/appli/EntitiesForm/Entrance/Cave/index.jsx
> +  errors: PropTypes.objectOf(),
`PropTypes.shape({})` plutôt que `objectOf` : ce dernier génère des erreurs car il est invalide quand vide

2022-01-10 10:10 UTC, Clm-Roig commented
De manière générale, concernant les PropTypes, il faut remplacer tous les : 
`errors: PropTypes.objectOf(),
control: PropTypes.objectOf(),`

par : 

`errors: PropTypes.shape({}),
control: PropTypes.shape({}),`

2022-01-10 10:17 UTC, Clm-Roig commented
Des majuscules aux labels des inputs seraient également les bienvenues :slightly_smiling_face: 
longitude, latitude, depth, length, language...

2022-01-12 14:44 UTC, urien commented
@Clm-Roig a écrit "Si je ne me trompe pas, lors que l'on "like to a network", les textes et la recherche rapide doivent se faire sur les networks."
En fait non il faut pouvoir raccrocher une entrée à une cave "simple" afin de constituer un "network"

2022-01-12 14:50 UTC, Clm-Roig commented
> @Clm-Roig a écrit "Si je ne me trompe pas, lors que l'on "like to a network", les textes et la recherche rapide doivent se faire sur les networks." En fait non il faut pouvoir raccrocher une entrée à une cave "simple" afin de constituer un "network"


Ah oui effectivement... J'ai corrigé mes commentaires pour aller dans ce sens.

2022-01-23 12:59 UTC, maximenathan commented on packages/web-app/src/features/QuickSearch.jsx
> +    'documents',
@Clm-Roig pour `searchOnType` & `searchOnTypes` ?

2022-01-23 13:14 UTC, Clm-Roig commented on packages/web-app/src/features/QuickSearch.jsx
> +    'documents',
oui !

2022-01-23 13:47 UTC, maximenathan commented
> la possibilité de mettre une

J'ai pris en compte tes recommendations
Par contre ce n'est pas vraiment possible d'avoir des descriptions au niveau de l'Entrance

Pour l'instant les descriptions sont seulement rattachées à la cave
si je ne me trompe pas @Clm-Roig ?

2022-01-23 15:21 UTC, urien commented
Bravo ! c'est super.
Concernant ma proposition pour la location je propose donc que tu retire la description quand on créé une cavité qui n'est pas rattachée à un réseau
![image](https://user-images.githubusercontent.com/1165144/150685584-7d43fe7f-b209-40c3-9871-eff9085edd46.png)

2022-01-23 15:42 UTC, urien requested changes
Cela fonctionne très bien mais je crois tu as modifié le fonctionnement et désormais quand on souhaite associer une entrée à un réseau existant dans le champ de recherche tu ne proposes que les networks. 
C'est un problème car cela empêche de créer un network en associant une entrée à une cavité avec une seule entrée

2022-02-01 02:17 UTC, bsoufflet commented
![image](https://user-images.githubusercontent.com/985903/151903469-e58ef164-89a1-4c2a-9816-099104100274.png)
`Title language` -> `Entrance name language`
![image](https://user-images.githubusercontent.com/985903/151903534-0a8f3c8f-cb01-45a4-aeea-8fb9f0a77200.png)
`Linked to an existing network`
`First entrance of the cave (on Grottocenter)`
(@urien : tu penses quoi de ces changements pour le premier choix lors de la création ?)
J'enlèverai aussi `An entrance must be attached to an existing cave` car ca apporte plus de confusion que d'information.

2022-02-01 10:10 UTC, urien commented
Effectivement cela sera beaucoup plus clair pour les utiisateurs

2022-02-13 11:17 UTC, urien reviewed
Quand je créé une cavité à partir d'un réseau existant la procédure aboutit, quand je créé une nouvelle cavité le clic sur "create" ne provoque rien

2022-02-13 21:36 UTC, maximenathan commented
> Quand je créé une cavité à partir d'un réseau existant la procédure aboutit, quand je créé une nouvelle cavité le clic sur "create" ne provoque rien

C'est corrigé :ok_hand:

2022-02-13 22:01 UTC, urien approved these changes

2022-02-13 22:02 UTC, urien approved these changes
C'est parfait

2022-02-17 10:26 UTC, merged