feat(#661) Internal link on creator nickname
GrottoCenter/grottocenter-front pull request #666
Opened 2022-07-26 08:29 UTC by clemsix6

2022-07-26 09:00 UTC, Clm-Roig commented
Y a un petit problème avec ESLint (cf les checks "not successful" de la PR) : 
![image](https://user-images.githubusercontent.com/20704943/180967581-af3ff1ed-119e-4b8e-b311-3feeceabba8e.png)

2022-07-26 17:01 UTC, urien requested changes
Beau travail.
Est ce que vous pouvez ajouter un espace entre le nom et le tiret ?
Le ticket concernait aussi le nom qui est est en bas à gauche. Je vous propose de réaliser la petite modification ci-dessus pour que je valide votre PR. Il faudrait faire un rebase -i pour fusionner les commits pour qu'il n'y en ai plus qu'un

2022-07-26 20:51 UTC, Clm-Roig commented
Cette PR est très similaire à #667 et utilise les mêmes fonctions : peut-être devrions-nous les fusionner pour pouvoir faciliter le refactoring et la lisibilité des deux PRs qui se ressemblent énormément ?

2022-08-01 17:03 UTC, Clm-Roig commented
Je ferme cette PR vu que #667 réunit maintenant les deux features.

2022-08-01 17:03 UTC, closed without merging