496 link on author name
GrottoCenter/grottocenter-front pull request #667
Opened 2022-07-26 13:26 UTC by clemsix6

2022-07-26 18:59 UTC, urien approved these changes
Cela fonctionne très bien. Merci

2022-07-26 19:06 UTC, urien commented
Là aussi il faudrait faire un rebase -i pour ne garder qu'un commit sur cette issue

2022-07-26 20:49 UTC, Clm-Roig requested changes

2022-07-26 20:49 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Comments.jsx
> +      <label>
`eslint-disable` ne doit être utilisé que pour une excellente raison, raison qui doit être mentionnée par un commentaire juste avant. 

Ici je pense que le `<label>` n'est pas utile : authorLink va être wrappé par un `Typography` plus bas qui lui donnera la bonne apparence.

2022-07-26 20:49 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Descriptions/Description.jsx
> +    );
Ce bout de code est répété plusieurs fois : il serait judicieux de le refactoriser dans un fichier placé dans /utils par exemple.

2022-07-26 20:49 UTC, Clm-Roig commented on packages/web-app/src/pages/DocumentDetails/transformers.js
> +});
À refactoriser dans un fichier à part et à remplacer partout où c'est utilisé.

2022-07-27 16:23 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Comments.jsx
> +      <label>
@YohanHATOT tu peux "resolve" mes commentaires ci-dessous 👇 si jamais tes derniers commits résolvent le problème. Comme ça je sais quand c'est résolu ou pas et donc, faire une review en conséquence. 

Tu peux d'ailleurs me redemander une review quand tu estimes que la PR est prête à être re-review 🙂 (en haut à droite de la PR)

2022-07-27 16:59 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Comments.jsx
> +      <label>
@clemsix6 je te taggue aussi pour que tu vois mes 2 précédents commentaires. Ce sera valable pour toutes vos PRs 🙂

2022-07-27 17:09 UTC, Clm-Roig requested changes

2022-07-27 17:09 UTC, Clm-Roig commented on packages/web-app/src/pages/DocumentDetails/transformers.js
> +});
Je réitère ce commentaire en le précisant. Il faudrait mettre cette fonction dans le dossier `src/util`. Ça sert à pleins de transformers, on ne peut pas le laisser dans `DocumentDetails/transformers.js`.

2022-07-28 10:41 UTC, Clm-Roig requested changes
Mes commentaires n'ont toujours pas été résolus... Un souci ?

2022-07-28 17:28 UTC, Clm-Roig requested changes
Pensez à Resolve mes commentaires résolus par vos derniers commits : ça permettra à tout le monde d'y voir plus clair sur cette PR 🙂

2022-07-28 17:28 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/utils.js
> +  );
Il s'agit d'un composant React qui render quelque chose donc ; 
- A renommer `AuthorLink`
- A déplacer dans `components/common/AuthorLink/index.js`

Après en avoir fait un composant React, il faut utiliser `const { formatMessage } = useIntl()` pour traduire la partie "Posted by". 

Enfin, il serait bien de rajouter le cas où le nickname et l'id ne sont pas connus. Quelque chose comme "Posted by an unknown author".

2022-07-29 14:35 UTC, Clm-Roig requested changes

2022-07-29 14:35 UTC, Clm-Roig commented on packages/web-app/src/components/common/AuthorLink/index.js
> +    <span>{formatMessage({ id: 'Posted by' })} unknown author</span>
`unknown author` fait partie de la chaîne de traduction : 

`formatMessage({ id: 'Posted by an unknown author' }`

@urien ça te paraît bien comme message quand on ne connaît pas l'auteur ?

2022-07-29 14:35 UTC, Clm-Roig commented on packages/web-app/src/util/GetAuthor.js
> +export default getAuthor;
Le nom du fichier doit être `getAuthor` (fonction utilitaire) et pas `GetAuthor` (composant).

2022-07-29 16:42 UTC, Clm-Roig requested changes

2022-07-29 16:42 UTC, Clm-Roig commented on packages/web-app/src/components/common/AuthorLink/index.js
> +      {formatMessage({ id: 'unknow author' })}
Y a un souci ici... Le nickname et l'url ont disparu avec le dernier commit.

2022-07-29 16:48 UTC, Clm-Roig requested changes

2022-07-29 16:48 UTC, Clm-Roig commented on packages/web-app/src/util/getAuthor.js
> +  surname: author?.surname || 'Unknown',
Les `|| Unknown` devrait disparaître je pense, parce que sinon on est incapable de savoir quand un auteur a un nom, prénom, surnom ou pseudo depuis un composant. 

Charge à celui qui appelle `getAuthor()` de vérifier si les valeurs retournées sont undefined ou pas.

2022-08-01 16:29 UTC, Clm-Roig commented
Ok ça m'a l'air bon ! Je vais juste rebase tous les commits en 1 ou 2 commits et ajouter le "authorLink" à 2-3 endroits supplémentaires (tant qu'on y est) et j'approuve la PR :slight

2022-08-01 17:06 UTC, Clm-Roig commented
Le déploiement de preview sera prêt d'un instant à l'autre. @urien tu pourras confirmer que tout est ok ? 🙂 J'approuve la PR pour le code en tout cas, c'est tout bon.

2022-08-01 17:06 UTC, Clm-Roig approved these changes

2022-08-01 17:27 UTC, urien approved these changes
C'est super, tout marche bien

2022-08-02 12:15 UTC, merged