feat(#648): make identifier clickable
GrottoCenter/grottocenter-front pull request #678
Opened 2022-08-02 12:59 UTC by YohanHATOT

2022-08-02 13:16 UTC, urien approved these changes
Au point de vue fonctionnement c'est parfait. L'Université de Floride du Sud va être ravie
Merci beaucoup

2022-08-02 15:36 UTC, Clm-Roig commented
J'ai un souci avec cette URL qui ne commence pas par http : 
https://orange-rock-0d4f87503-678.westeurope.azurestaticapps.net/ui/documents/126633

2022-08-02 15:51 UTC, Clm-Roig requested changes
La logique du code n'est pas bonne et fait que ça ne fonctionne pas tout le temps (voir mon commentaire sur `transformers.js`.

Je vous mets 3 documents pour lesquels votre code doit fonctionner ;
- 126198 (url commençant par http)
- 126633 (url commençant par www)
- 21494 (identifiant n'étant pas un url)

2022-08-02 15:51 UTC, Clm-Roig commented on packages/web-app/src/pages/DocumentDetails/transformers.js
> +
Ce code ne fait... rien.
Regardez d'où vient l'identifier affiché à l'écran dans la page d'un document : il provient de `details.identifier`.
`details` quant à lui est construit grâce à `makeDetails()` un peu plus haut. 

Ce que je vous conseille : 
- faire de "identifier" un attribut plus complexe que juste une chaîne de caractères (3 attributs "string" : identifierType, identifier et url, avec **url** construit uniquement si identifierType === 'url')
- dans DocumentDetails/index.jsx, comme vous l'avez déjà fait, passer l'url pour la section "identifier" : 
```js
{ 
  label: formatMessage({ id: 'Identifier' }),
  value: details.identifier,
  url: identifier
}
```

N'hésitez pas à me demander si c'est pas clair.

2022-08-02 15:51 UTC, Clm-Roig commented on packages/web-app/src/pages/DocumentDetails/index.jsx
> +  identifier: PropTypes.string,
A supprimer, `details` contient déjà identifier + voir mon commentaire sur transformers.js.

2022-08-02 15:51 UTC, Clm-Roig commented on packages/web-app/src/pages/DocumentDetails/index.jsx
> +      identifier={makeIdentifier(details || {})}
A supprimer, `details` contient déjà identifier + voir mon commentaire sur transformers.js.

2022-08-02 15:51 UTC, Clm-Roig commented on packages/web-app/src/pages/DocumentDetails/index.jsx
> +  identifier
A supprimer, `details` contient déjà identifier + voir mon commentaire sur transformers.js.

2022-08-02 15:51 UTC, Clm-Roig commented on packages/web-app/src/pages/DocumentDetails/index.jsx
> +  makeIdentifier
A supprimer, `makeDetails` retourne déjà l'identifier + voir mon commentaire sur transformers.js.

2022-08-03 12:50 UTC, urien commented
A partir des exemples de Clément
Cela fonctionne pour 126198
cela ne fonctionne pas pour 126633 (URL commençant par www)
pour 21494 il y a un lien alors qu'il ne devrait pas y en avoir car ce n'est pas une URL

2022-08-03 12:59 UTC, Clm-Roig commented
Pensez à tester sur vos machines avec les ids que je vous ai indiqué plus haut **AVANT** de pusher 🙂

2022-08-03 13:02 UTC, YohanHATOT commented
> 

Désolé, j'ai push pour que @clemsix6  puisse-avoir accès à mes nouvelles modifications afin de résoudre les problèmes, que vous avez identifié.

2022-08-03 13:08 UTC, Clm-Roig commented
Ok alors dans ce cas-là, on peut utiliser un autre workflow : 
- Vous demandez une review à Frédéric et moi (via l'interface, en haut à droite)
- On approuve tous les deux (cas idéal) → vous mergez, c'est fini ✔️ 
- L'un de nous refuse. 
- Vous pushez une modif.
- Vous redemandez une review. 

Et là seulement, on ouvre la PR et on la review 🙂 Ça demande quelques efforts de tout le monde :
- Que vous pensiez à demander des reviews aux bons moments.
- @urien et moi qu'on surveille bien que notre validation est dans le bon état. Par exemple, là, tu es en "approuvé" alors que tu n'est pas d'accord avec les dernières modifications. Il faut que tu le changes pour qu'on sache tous où on en est.

2022-08-03 13:12 UTC, urien requested changes
Ok

2022-08-03 14:08 UTC, urien approved these changes
C'est parfait maintenant pour les 3 id que Clément avait proposé

2022-08-03 14:43 UTC, Clm-Roig requested changes

2022-08-03 14:43 UTC, Clm-Roig commented on packages/web-app/src/pages/DocumentDetails/transformers.js
> +    isUrl: formatedIdentfier.startsWith('http'),
Cet attribut est inutile. On a déjà cette information dans `data.identifierType.id` qui vaudra `"url"` si c'est bien un URL.

Donc la bonne solution selon moi pour éviter de créer un nouvel attribut (ce n'est pas le rôle du transformer), c'est la suivante : 

```js
return {
  identifier: data.identifier, // ici le pathOr() n'est pas nécessaire il me semble : si y a pas identifier, ça renvoie undefined
  identifierType: data.identifierType?.id 
    // ici la notation "?id" permet de conditionnellement obtenir l'id, que s'il est présent. 
    // ça vient remplacer pathOr d'une certaine manière.
  }
  // ... les autres attributs
}
```
Ainsi dans index.js, il suffira de faire :
```js
 value: details.identifier?.value,
 url: details.identifierType === 'url' ? details.identifier?.url : undefined
``` 

Le composant gérera tout seul le cas où l'url est "undefined" 🙂 Et pour l'histoire du https ou http ou www ce n'est pas à vous de gérer. On affiche l'url, même s'il est incorrect. Les utilisateur le modifieront si besoin, c'est leur responsabilité.


Pour résumer, le transformer n'a pas à ajouter des propriétés calculées comme `isUrl`. Vous devez juste l'améliorer pour inclure plus d'informations que ce que vous aviez déjà. Les notations "?id" et les conditionnelles "condition ? cas true : cas false"  sont un peu déroutants de prime abord mais sont surpuissantes pour écrire du code compact et très utilisées dans React 😉

2022-08-06 21:01 UTC, closed without merging