feat(#306): Button to view the cave on OSM
GrottoCenter/grottocenter-front pull request #710
Opened 2022-08-08 14:11 UTC by clemsix6

2022-08-08 16:50 UTC, urien commented
Le bouton est actif, mais le lien ne fonctionne pas

pour cette entrance, le lien conduit à https://orange-rock-0d4f87503-710.westeurope.azurestaticapps.net/ui/map/bG5nPTE5LjAwNjM0NzY1NjI1MDAwNCZsYXQ9NDYuNzE3OTM5OTMzNTA2MjMmem9vbT02
qui n'est pas une page OSM

2022-08-12 11:12 UTC, urien commented
Pour les cavités sensibles, les coordonnées ne sont pas disponibles, il faudra que le bouton soit inactif

Exemple : https://grottocenter.org/ui/entrances/5655

2022-08-15 08:00 UTC, maximenathan commented on packages/web-app/src/components/common/Layouts/Fixed/ActionBar.jsx
> +          // eslint-disable-next-line react/jsx-closing-bracket-location
C'est une règle qui peut être fix automatiquement il me semble

Peut etre un problème de config d'eslint? :thinking:

2022-08-15 08:02 UTC, maximenathan commented
De manière générale, une petite description de la PR serait top :pray:

2022-08-17 07:34 UTC, urien approved these changes
Pour moi le fonctionnement est parfait.

Merci

2022-08-17 15:24 UTC, urien commented
Et maintenant c'est ok pour les cavités pour lesquelles les coordonnées ne sont pas accessibles

2022-08-19 13:29 UTC, Clm-Roig requested changes
Juste 2 petits commentaires à régler, sinon c'est bon.

2022-08-19 13:29 UTC, Clm-Roig commented on packages/web-app/src/components/common/Layouts/Fixed/ActionBar.jsx
> +  const longitude = propOr(undefined, 1, position);
`propOr` est inutile ici. Si `position` est bien un tableau et que `position[0]` n'existe pas, ça renvoie bien undefined automatiquement.

Attention à ne pas trop complexifier le code pour rien : des fois le "vanilla" Javascript a déjà la réponse à votre problème 🙂

2022-08-19 13:32 UTC, Clm-Roig commented
@clemsix6 il faudrait que tu rajoutes "Fix #306" dans ton premier message de la PR pour que ça ferme l'issue automatiquement quand la PR est mergée.

2022-08-22 16:46 UTC, Clm-Roig commented
@clemsix6 Si tu penses que tes modifs sont terminées et que tu as besoin d'une revue de code, il faut que tu me la demandes en utilisant le bouton en haut à droite de la PR.

2022-09-10 08:50 UTC, Clm-Roig requested changes
Désolé pour le retard de review, j'ai pas reçu le mail comme quoi je devais review...

2022-09-10 08:50 UTC, Clm-Roig commented on packages/web-app/src/components/common/Layouts/Fixed/ActionBar.jsx
>          label={formatMessage({ id: 'Map' })}
Je changerai bien le label en tooltip, voire même l'icône. En voyant l'icône de carte, je m'attends à ce que ça ouvre la carte de Grottocenter.

![Sans titre édit](https://user-images.githubusercontent.com/20704943/185630918-c15b0522-0c18-4d8e-9bb8-6ebbbd6da89c.png)


Quelque chose comme "Open on OpenStreetMap" pour le label et le logo d'OpenStreetMap pour l'icône. Qu'en penses-tu @urien ?

2022-09-10 08:50 UTC, Clm-Roig commented on packages/web-app/src/components/common/Layouts/Fixed/ActionBar.jsx
> +          // eslint-disable-next-line react/jsx-closing-bracket-location
@clemsix6 il y a toujours un souci ici

2022-09-10 08:50 UTC, Clm-Roig commented on packages/web-app/src/components/common/Layouts/Fixed/ActionBar.jsx
>          label={formatMessage({ id: 'Map' })}
Le changement de texte du Tooltip est toujours à faire @clemsix6 "Open on OpenStreetMap".

2022-09-10 09:07 UTC, urien commented on packages/web-app/src/components/common/Layouts/Fixed/ActionBar.jsx
>          label={formatMessage({ id: 'Map' })}
Oui tes propositions le semblent tout à fait pertinentes

2022-09-14 15:54 UTC, urien approved these changes
Cela fonctionne : bouton actif quand il y a des coordonnées, bouton inactif quand les coordonnées sont masquées. Texte revu quand la souris passe sur le bouton

Merci

2022-09-14 16:24 UTC, Clm-Roig approved these changes
C'est tout bon pour moi 🙂

2022-09-15 15:57 UTC, merged