feat(login): add password need reset view
GrottoCenter/grottocenter-front pull request #773
Opened 2022-11-27 17:37 UTC by vmarseguerra

# Add the "password need reset" view after login

Linked to https://github.com/GrottoCenter/grottocenter-api/pull/1062

2022-11-27 18:01 UTC, urien commented
Je viens de faire un test, je me suis authentifié mais la fenêtre ne s'est pas ouverte. Peut-être faut-il que le back soit déployé ?

2022-11-28 00:10 UTC, bsoufflet commented on packages/web-app/src/components/appli/Login.jsx
> +          For security reasons please create a new password.
@urien : Il faudra traduire ces phrases dans la plupart des langues au plus vite je pense, pour que dès le deploiement de cela nos utilisateurs voient le message dans leur langue...

(il y a d'autres <translate> plus haut et plus bas)

Je ne sais pas comment bien faire cela... Actuellement c'est souvent après le deploy que les traduction sont faites via une PR de l'outil de traduction...

2022-11-28 00:11 UTC, bsoufflet approved these changes

2022-11-28 00:17 UTC, bsoufflet requested changes
@vmarseguerra : Il faudrait ajouter les nouvelles phrases à traduire dans en.json (et pourquoi pas aussi optionnellement dans fr.json).
il faut utiliser l'ordre alpha dans ces fichiers.
Les autres traductions seront faites par les traducteurs via transifex

cf : https://github.com/GrottoCenter/grottocenter-front/wiki/Translation-workflow#developers

2022-11-28 08:22 UTC, Clm-Roig commented
@bsoufflet Non pas dans fr.json, je crois que ça pose un problème de conflits. Comme stipulé dans le lien que tu as mis, c'est uniquement dans en.json.

2022-11-28 22:32 UTC, bsoufflet commented
> @bsoufflet Non pas dans fr.json, je crois que ça pose un problème de conflits. Comme stipulé dans le lien que tu as mis, c'est uniquement dans en.json.

@Clm-Roig : On a donc pas moyen de traduire en francais en amont d'une release du front ? Il faut le faire rapidement après une release ?

2022-11-28 22:33 UTC, bsoufflet approved these changes

2022-11-28 22:35 UTC, Clm-Roig commented
Je ne crois pas... Il me semble que si j'ai écrit de modifier seulement le fichier en.json, c'est bien parce qu'il y avait un souci avec le fr.json. 

Un test rapide pourrait nous ôter le doute. Il faut bien vérifier que la synchronisation Transifex <-> GitHub persiste et n'écrase rien, autant en anglais qu'en français dans ce cas-là.

2022-11-28 23:29 UTC, bsoufflet commented
> Je ne crois pas... Il me semble que si j'ai écrit de modifier seulement le fichier en.json, c'est bien parce qu'il y avait un souci avec le fr.json.
> 
> Un test rapide pourrait nous ôter le doute. Il faut bien vérifier que la synchronisation Transifex <-> GitHub persiste et n'écrase rien, autant en anglais qu'en français dans ce cas-là.

Ok, pour cette PR on fera comme d'habitude. @urien il faudra juste etre réactif sur les traductions (principalement le FR) pour que les utilisateurs voient les messages de changement de mot de passe en francais si possible ;)

2022-11-29 08:53 UTC, Clm-Roig approved these changes

2022-11-29 23:47 UTC, merged