feat(#770): error boundary component
GrottoCenter/grottocenter-front pull request #774
Opened 2022-11-29 10:20 UTC by Clm-Roig

# Error boundary

Fix #770

## 🤔 What  
When an error occurs, instead of displaying a white page, the app displays an error message with various information:

![Screenshot 2022-11-29 at 11-02-55 Grottocenter v3](https://user-images.githubusercontent.com/20704943/204502469-72bf9977-a774-4a21-bed3-103166f5648c.png)

The user can continue to browse the website too.

In case something REALLY wrong happens (at the app root level, it never happened in the past years), a big error message is displayed in fullscreen :

![gc grosse erreur](https://user-images.githubusercontent.com/20704943/204502736-7c2d4be3-37f6-48c8-a381-4be3cd31a750.png)

## 🤷‍♂️ Why  
Inform the user about the error and let him browse the website again.

## 🔍 How  
I added an `ErrorBoundary` component as explained here: https://reactjs.org/docs/error-boundaries.html

## 🧪 Testing
To test this feature, throw an Error in any component: 
- For the "small" error, the component should be a children of the app layout (any page will do it, Person, Massif, Home, Advanced search...)
- For the "big" error, thrown the Error from Application.jsx for example.

2022-11-29 10:43 UTC, urien reviewed
Peut être que c'est un cas qui n'est pas pris en charge, mais quand on demande une ressource qui n'existe pas on n’accède pas au message indiqué
![image](https://user-images.githubusercontent.com/1165144/204507168-3475c816-b831-4645-8fb3-fb173cc4c5f5.png)
Quand je lui soumets un chemin idiot il a l'air content
![image](https://user-images.githubusercontent.com/1165144/204508058-9a93b992-9ca2-41d3-9abe-e496eea4060c.png)
Quand je lui indique l'URL d'un fichier qui n'existe pas  la réponse est celle-ci
![image](https://user-images.githubusercontent.com/1165144/204508402-400c49b7-7444-484d-86a7-53e95694bc7f.png)

2022-11-29 10:51 UTC, Clm-Roig commented
@urien 

> Ressource qui n'existe pas

Effectivement, une ressource non trouvée n'est pas une erreur. Ce sont 2 composants différents qui gèrent ces cas-là.

> Chemin "idiot"

Il s'arrête à /search qui lui convient, qu'importe ce qu'il y a après. Pareil, c'est géré par un autre composant que celui concerné par cette PR.

> Fichier qui n'existe pas

Tu es sur le site d'Azure là, pas sur Grottocenter. On n'a pas la main sur cette page.


De manière générale, je ne vois pas trop comment tu peux tester cette PR... On a aucun bug connu qui plante l'application actuellement (et tant mieux !) 😅 
J'ai dû "forcer" des erreurs manuellement dans le code pour développer cette fonctionnalité. D'où mes screenshots pour que tu puisses me valider l'apparence des erreurs et les textes qui vont avec. Ce composant remplacera les "écrans blancs" qu'on a pu avoir par le passé et permettra ainsi à l'utilisateur de continuer à naviguer malgré les erreurs.

2022-11-29 10:54 UTC, urien approved these changes
Ok, du coup c'est parfait

2022-11-29 22:37 UTC, bsoufflet requested changes

2022-11-29 22:37 UTC, bsoufflet commented on packages/web-app/src/App.jsx
> +                            Refresh the page to browse Grottocenter again.
Ne faudrait il pas plutot écrire : 
`<a>Go back to the home page of Grottocenter</a>`
car j'ai peur que le refresh fasse revenir la meme erreur car on sera surement sur l'URL qui sera problématique non ?

2022-11-29 22:37 UTC, bsoufflet commented on packages/web-app/src/App.jsx
> +                            Refresh the page to browse Grottocenter again.
On pourrait également proposer un lien <a>Go back to the previous page you visited</a>

2022-11-29 22:37 UTC, bsoufflet commented on packages/web-app/src/components/appli/ErrorBoundary/ErrorBoundaryInner.jsx
> +                  client GitHub repository.
You can also directly create a new issue on the Grottocenter GitHub page.

2022-11-29 22:37 UTC, bsoufflet commented on packages/web-app/src/components/appli/ErrorBoundary/ErrorBoundaryInner.jsx
> +              &nbsp; &nbsp;
Il ne manque pas des translate sur Go back et sur Go to home page ?

2022-11-30 09:06 UTC, Clm-Roig commented
@bsoufflet je te rejoins sur tous tes commentaires. Je n'avais pas trop d'idée pour la "grosse" erreur alors qu'il suffirait d'afficher exactement le même composant que pour la "petite" erreur (toutes les infos pour report le problème + les deux boutons). Je fais ça de suite.

2022-11-30 09:17 UTC, bsoufflet approved these changes

2022-11-30 09:36 UTC, Clm-Roig commented on packages/web-app/src/components/appli/ErrorBoundary/index.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Il me reste ça à corriger avant de merge

2022-11-30 11:53 UTC, merged