Entity refactor for: Location, Description, Rigging, History, Comment
GrottoCenter/grottocenter-front pull request #779
Opened 2022-12-04 16:14 UTC by vmarseguerra

Main changes are:
- Adapts entities to the new data format
- Lists explicitly possible parameters for entities actions
- Normalizes Contribution call to always include the author and reviewer
- Normalizes usage of checkAndGetStatus for entities action responses
- Preserves element order when updating an array in React state
- Simplify rating calculation

Linked with: https://github.com/GrottoCenter/grottocenter-api/pull/1074

2022-12-04 23:20 UTC, bsoufflet approved these changes

2022-12-06 22:18 UTC, maximenathan requested changes
Thanks for the refactor :bow: 

Left only one blocking comment

2022-12-06 22:18 UTC, maximenathan commented on packages/web-app/src/reducers/EntranceReducer.js
> +function arrFindReplaceOrAdd(arr, test, replacement) {
Let's not mutate the redux store

[redux doc](https://redux.js.org/usage/structuring-reducers/immutable-update-patterns#inserting-and-removing-items-in-arrays)

If necessary, we can get inspiration from redux examples or use a small dependency like [immer](https://github.com/immerjs/immer)

2022-12-13 00:12 UTC, bsoufflet commented
A merge sur develop dès que le back est deploy :)

2022-12-14 00:53 UTC, merged