feat(entrance): new deleted entrance page
GrottoCenter/grottocenter-front pull request #788
Opened 2022-12-16 00:23 UTC by bsoufflet

# new deleted entrance page

Fix #780 

## 📸 Previews
![image](https://user-images.githubusercontent.com/985903/207994103-598a01f9-231b-4ce2-8f38-d990a7288963.png)

2022-12-16 00:26 UTC, bsoufflet commented
A next step for this feature in the future would be to allow a moderator to recover a deleted entrance from this page !

The group work on versioning should also display the "full history" icon on this page to be able to see the hsitory of a deleted entrance ! @julien-vendran

2022-12-16 10:39 UTC, Clm-Roig requested changes

2022-12-16 10:39 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/DeletedEntrance.jsx
> +      disableMargins
Il faudrait peut-être utiliser le `FixedLayout` ici pour positionner la page sur une carte comme toutes les autres pages.

2022-12-16 10:39 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/DeletedEntrance.jsx
> +`;
Pour éviter des paddings / margins qui varient d'un développeur à un autre, le mieux c'est d'utiliser le theme avec styled, puis de faire `theme.spacing(x)` avec `x` l'espacement de ton choix. 

```js
const ToggleButtonGroup = styled(MuiToggleButtonGroup)`
  padding: ${({ theme }) => theme.spacing(2)}px;
`;
```

Cont = Container ? Je ne suis pas trop fan des abbréviations pour les noms de variables. Sinon, on utilise souvent `Styled` comme préfixe (ici : `StyledLink` et `StyledAuthor` donc).

2022-12-16 10:39 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/DeletedEntrance.jsx
> +            )}
Les `<div>` sont indispensables pour la mise en page j'imagine ?

2022-12-16 13:27 UTC, julien-vendran commented
> A next step for this feature in the future would be to allow a moderator to recover a deleted entrance from this page !
> 
> The group work on versioning should also display the "full history" icon on this page to be able to see the hsitory of a deleted entrance ! @julien-vendran

2022-12-18 00:23 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/DeletedEntrance.jsx
> +            )}
Je viens de remplacer les 2 div par un style css ;)

2022-12-18 00:23 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/DeletedEntrance.jsx
> +`;
done !

2022-12-18 00:23 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/DeletedEntrance.jsx
> +      disableMargins
done !

2022-12-18 00:25 UTC, bsoufflet commented
![Screenshot from 2022-12-18 01-16-15](https://user-images.githubusercontent.com/985903/208271221-f1ee7f71-f8b4-440a-be54-36f7066daf30.png)
Nouveau design en utilisant un "Layout" (card material) suite à la remarque de @Clm-Roig :)

2022-12-18 06:50 UTC, urien commented
Normalement l'entrance 3706 est supprimée. Quand je vais à l'adresse 
https://orange-rock-0d4f87503-788.westeurope.azurestaticapps.net/ui/entrances/3706
J'ai un message rouge en bas me disant que la ressource n'existe pas

2022-12-18 09:30 UTC, Clm-Roig approved these changes

2022-12-18 09:31 UTC, Clm-Roig commented
> Normalement l'entrance 3706 est supprimée. Quand je vais à l'adresse https://orange-rock-0d4f87503-788.westeurope.azurestaticapps.net/ui/entrances/3706 J'ai un message rouge en bas me disant que la ressource n'existe pas

C'est normal, il faut que https://github.com/GrottoCenter/grottocenter-api/pull/1083 soit mergée et déployée en production pour que ça marche. 
(je confirme au passage que l'entrée que tu mentionnes est bien en BD et bien marquée comme "deleted")

2022-12-18 18:16 UTC, urien commented
Pourquoi pas indiquer que la PR est liée à une PR côté back

2022-12-18 22:42 UTC, bsoufflet commented
> Pourquoi pas indiquer que la PR est liée à une PR côté back

C'est bien écrit dans la description de la PR tout en haut ;)

> Linked to : https://github.com/GrottoCenter/grottocenter-api/pull/1083

2022-12-18 22:56 UTC, bsoufflet commented
@urien @Clm-Roig : Je viens de modifier le template des PR :)

2022-12-19 00:06 UTC, merged