feat(deleted): properly display deleted entities
GrottoCenter/grottocenter-front pull request #805
Opened 2022-12-26 23:28 UTC by bsoufflet

# Properly display deleted entities like Massif, Document, ...

## 🤔 What  
New deleted pages for : 
- Document
- Network
- Massif
- Organization

## 🤷‍♂️ Why  
To fix #804 
These deleted pages may be improved later to allow the moderator to "recover" a "Deleted" entity which shouldn't be deleted.

## 🔗 Related API PR
https://github.com/GrottoCenter/grottocenter-api/pull/1084

_Usually it means that the "Azure Static Web Apps" stage site 
won't work at 100% to test this PR as long at the API PR is 
not merged and deployed._

## 📸 Previews
![image](https://user-images.githubusercontent.com/985903/209588279-e8884967-e9e5-42ef-b72c-8211fe7af6ec.png)

![image](https://user-images.githubusercontent.com/985903/209588288-f540eed0-d46b-4d24-bd86-0e719d93d348.png)

![image](https://user-images.githubusercontent.com/985903/209588294-ac673711-a3e4-4e19-b909-05b1b4cad2dd.png)

![image](https://user-images.githubusercontent.com/985903/209588301-ae7efbd3-5ab3-4ceb-94ac-b19512a60519.png)

2022-12-27 09:24 UTC, vmarseguerra approved these changes

2022-12-29 14:15 UTC, Clm-Roig requested changes

2022-12-29 14:15 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Riggings/Riggings.jsx
> +              {riggings
```js
riggings.length > 0 && riggings.sort(...
```

2022-12-29 14:15 UTC, Clm-Roig commented on packages/web-app/src/pages/Entry/transformers.js
> +  localisation: `${data.city}, ${data.region}, ${data.country}`, // TODO rename to location
Un TODO qui subsiste ici

2022-12-29 14:15 UTC, Clm-Roig commented on packages/web-app/src/pages/Massif/transformers.js
> +      reviewer: description?.reviewer ? getAuthor(description?.reviewer) : null,
Vu le code défensif de `getAuthor()`, tu n'as pas besoin de faire ce check : tu peux directement faire `getAuthor(description?.reviewer)`

Je viens de tester sur ma machine en passant `null`, `undefined` ou `{}` à getAuthor() et ça fonctionne.

2022-12-30 00:23 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/Riggings/Riggings.jsx
> +              {riggings
@Clm-Roig : quel est l'intéret de mettre le sort ici ?

2022-12-30 00:25 UTC, bsoufflet commented on packages/web-app/src/pages/Entry/transformers.js
> +  localisation: `${data.city}, ${data.region}, ${data.country}`, // TODO rename to location
En effet, je ne pensais pas que le refcator de localisation en location dans toute l'app était quelque chose à faire dans cette PR... J'ai donc bien nommé dans mon composant "location" et j;ai mis un TODO poru se rappeler que localisation n'est pas en anglais ce que l'on a cherché à dire...

2022-12-30 16:41 UTC, Clm-Roig commented on packages/web-app/src/pages/Entry/transformers.js
> +  localisation: `${data.city}, ${data.region}, ${data.country}`, // TODO rename to location
Ah d'acc, je croyais que c'était que ici et que majoritairement on utilisait bien `location` dans toute l'app.

2022-12-30 16:41 UTC, Clm-Roig commented on packages/web-app/src/components/appli/Entry/Riggings/Riggings.jsx
> +              {riggings
Juste pour être plus compact et éviter d'utiliser un React Fragment <>

2022-12-30 23:32 UTC, bsoufflet commented
@Clm-Roig Tu peux verifier ;)

2022-12-31 09:20 UTC, Clm-Roig approved these changes

2022-12-31 23:03 UTC, merged