Feature/polytech entrance snapshots
GrottoCenter/grottocenter-front pull request #836
Opened 2023-02-02 10:50 UTC by julien-vendran

# Your PR title here

## 🤔 What  
Add general entrance page

## 🤷‍♂️ Why  
PFE Polytech

## 🔗 Related API PR
Already merged

2023-02-02 21:54 UTC, bsoufflet commented
@julien-vendran Attention ! Je suis désolé mais pour pouvoir review correctement cette PR j'ai du la rebase devant develop car elle incluait encore des commits de votre précédente branche ;) À prendre en compte sur votre git local.

2023-02-02 21:57 UTC, bsoufflet requested changes

2023-02-02 21:57 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/Snapshots/UtilityFunction.js
> +const PageVersionningButton = ({ id, isNetwork }) => (
On retrouve ici les mots versionning qu'il faudrait surement remplacer pour homogénéiser le vocabulaire

2023-02-02 23:14 UTC, bsoufflet commented
![image](https://user-images.githubusercontent.com/985903/216471940-cd63efbe-3126-4cc0-a3c1-60150e29713b.png)
- Il manque certainement l'affichage du type de l'élément modifié (location ou description ou ...) directement visible sur l'accordéon fermé.
- A quoi correspond "unknown" ? Un bug je pense car normalement il s'agit de la modif des properties de l'entrance il me semble pour certains cas.

2023-02-03 08:40 UTC, urien commented
Mêmes remarques que Benjamin
Nous avons beaucoup de lignes avec un contenu inconnu
Et nous ne savons pas ce qui a été modifié : entrée, description,
J'ai l'impression que vous récupérez bien les descriptions mais pas les autres éléments

2023-02-03 08:52 UTC, julien-vendran commented on packages/web-app/src/components/appli/Entry/Snapshots/UtilityFunction.js
> +const PageVersionningButton = ({ id, isNetwork }) => (
J'ai juste oublié de push cette modif 😅

2023-02-03 10:49 UTC, urien commented
Tout fonctionne : super !

2023-02-03 11:08 UTC, bsoufflet commented
![image](https://user-images.githubusercontent.com/985903/216584472-3575d413-53e4-4988-a559-6a7c540b1d60.png)
- Il manque le dernier changement pour chaque categorie.
Par exemple "cléo" a été modifié le 12/31/2022, 2:32 PM mais cen'est pas visible ici 

- La position du titre sur la ligne de l'accordéon n'est pas très esthétique... Serait il possible de revoir un peu cette ligne pour un rendu plus lisible ?
quelque chose comme ca par exemple ?
![image](https://user-images.githubusercontent.com/985903/216588791-2700d190-d6f5-4cde-b10c-fad170828b5b.png)

2023-02-03 11:10 UTC, bsoufflet commented
Il faudrait passer toutes les date en format un peu plus international (comme dans mon exemple au dessus) : 
JJ/MM/AAAA HH:MM
avec HH en mode 24h (et pas en mode 12h avec AM/PM)

2023-02-10 22:14 UTC, bsoufflet approved these changes

2023-02-10 22:14 UTC, merged