entrance-list
GrottoCenter/grottocenter-front pull request #840
Opened 2023-02-03 09:22 UTC by MargotGeorget

# Display entrance list 

## 🤔 What  
Get entrances list of a massif or a country from the API and display each entrances with its data quality in a new page

## 📸 Previews
<img width="822" alt="Screenshot 2023-02-03 at 10 20 23" src="https://user-images.githubusercontent.com/60788537/216561385-40595636-fc0f-46ac-9609-bed651fca69e.png">

2023-02-03 10:55 UTC, urien commented
C'est magnifique ! Bravo ! ici la liste des cavités de France a pris moins d'une minute
Je ne sais pas si c'est possible de trier les cavités dans le tableau par ordre alphabétique du nom ?

2023-02-03 23:42 UTC, bsoufflet commented
> C'est magnifique ! Bravo ! ici la liste des cavités de France a pris moins d'une minute Je ne sais pas si c'est possible de trier les cavités dans le tableau par ordre alphabétique du nom ?

@urien @MargotGeorget 
Désolé mais il me semble que le plus logique  / utile pour cette page serait un tri par note de qualité. On aurait ainsi un top des cavités d'un pays ayant le plus d'infos de qualité !

@urien 
Il faudrait ajouter un ticket pour rendre cette liste filtrable en ajoutant un champ "filter" au sommet de la liste où l'on pourrait du coup filtrer en fonction du nom de la cavité
Il faudrait ajouter un autre ticket pour afficher cette note dans la fiche d'une cavité (et pourquoi pas dans le résultat des recherches avancés)

2023-02-04 00:07 UTC, bsoufflet requested changes

2023-02-04 00:07 UTC, bsoufflet commented on packages/web-app/src/components/appli/StatisticsDataDashboard/index.jsx
> +    if (countryId) {
`setIsCountry(!!countryId)` -> pour enlever le if / else

2023-02-04 00:07 UTC, bsoufflet commented on packages/web-app/src/pages/EntrancesList/EntranceList.jsx
> +  return `${dateAsString} ${at} ${time} (${since} ${diffHours} h ${diffMins} min)`;
Je remplacerais bien tout cela par quelque chose de plus simple en utilisant date-fns qui est dispo aussi sur ce repo !

`last data update : about 1 hour`
`about 1 hour` sera directement fourni par formatDistanceToNow

https://date-fns.org/v2.29.3/docs/formatDistanceToNow

2023-02-04 00:07 UTC, bsoufflet commented on packages/web-app/src/pages/EntrancesList/index.jsx
> +        ? countryEntrances.sort((a, b) => a.name.localeCompare(b.name))
sort by score ?

2023-02-04 00:07 UTC, bsoufflet commented on packages/web-app/src/pages/EntrancesList/index.jsx
> +        ? massifEntrances.sort((a, b) => a.name.localeCompare(b.name))
sort by score ?

2023-02-05 07:33 UTC, urien commented
Fait
https://github.com/GrottoCenter/grottocenter-front/issues/844
https://github.com/GrottoCenter/grottocenter-front/issues/845

2023-02-05 07:52 UTC, urien commented
Concernant la date il y a peut être quelque chose à regarder. le 5-2-2023 à 8h52 j'ai cette information
![image](https://user-images.githubusercontent.com/1165144/216807832-130633b6-3d02-4d57-a8c1-afd7174196cd.png)
la date de mise à jour ne semble pas bonne, l'horaire est logique lui

2023-02-06 15:58 UTC, urien commented
Le tri est ok, la date aussi... mais du coup la tache Cron semble ne pas s'être executée depuis 4 jours
Pour moi c'est OK

2023-02-06 23:10 UTC, bsoufflet approved these changes

2023-02-06 23:10 UTC, merged

2023-02-06 23:18 UTC, bsoufflet commented
> Le tri est ok, la date aussi... mais du coup la tache Cron semble ne pas s'être executée depuis 4 jours Pour moi c'est OK

C'est moi qui n'avais pas activé le cron ;) C'est fait maintenant.