feat(dataHistory): restore snapshot
GrottoCenter/grottocenter-front pull request #859
Opened 2023-02-12 19:14 UTC by CecileDestIG

# [DRAFT] Restore Snapshot feature

## 🤔 What  
Restore a snapshot of an entry's entity with a button in the snaphot page.

## 🤷‍♂️ Why  
Restore an old version an entry's entity.

## 🔍 How  
_Create a new component RestoreSnapshot use in the snapshot page in the accordion.

2023-02-13 12:45 UTC, bsoufflet requested changes

2023-02-13 12:45 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/Snapshots/component/RestoreSnapshot.jsx
> +              id: content.t_id,
Utiliser le "spread" operator (...) pour tous les matching `x: content.x,`.
A faire pour ce case et pour ceux en dessous :)

exemple : 
```
updateComment({
              ...content,
              id: content.t_id,
              eTTrail: content.eTTrail.minutes,
              eTUnderground: content.eTUnderground.minutes
            })
```

2023-02-15 13:11 UTC, bsoufflet requested changes

2023-02-15 13:11 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/Snapshots/component/RestoreSnapshot.jsx
> +              id: content.t_id,
en fait il y a un petit problème de compréhension du "Spread" opérator...
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals
Celui-ci t'évite de faire : 
```
a: xx.a,
b: xx.b,
c: xx.c,
...
```
Il faudrait donc que tu es : 
```
updateComment({
              ...content,
              id: content.t_id,
              eTTrail: content.eTTrail.minutes,
              eTUnderground: content.eTUnderground.minutes
            })
```
et pas besoin d'écrire : 
```
              title: content.title,
              body: content.body,
              aestheticism: content.aestheticism,
              caving: content.caving,
              approach: content.approach,
              language: content.language
```

Meme remarque pour ci-dessous ;)

2023-02-15 15:03 UTC, urien commented
Je viens de faire un test rapide et cela fonctionne bien.
Ce qui est un peu déstabilisant c'est que le clic ne génère pas d'action sur la page. On voit le résultat sur la page de l'entrée en la rafraichissant. Mais c'est ce que vous nous avions indiqué.

2023-02-15 15:11 UTC, urien commented
Cela ne semble pas bien fonctionner pour les documents.  Ils ne se retrouvent pas dans la liste des documents devant être validés. Le plus simple serait de retirer cette fonctionnalité pour les documents à défaut de la rendre fonctionnelle

2023-02-16 00:02 UTC, bsoufflet approved these changes

2023-02-16 00:02 UTC, merged