Removes entrance country input + Adjusts coordinates formatting
GrottoCenter/grottocenter-front pull request #898
Opened 2023-03-31 17:31 UTC by vmarseguerra

In the entrance form, removes the country input as it is now set using the coordinates

Also adjust coordinates formatting (https://github.com/GrottoCenter/grottocenter-front/issues/878)

![image](https://user-images.githubusercontent.com/6350275/229187933-f89414df-7590-4a4f-a7f9-5458c1f85b1e.png)

## 🔗 Related API PR
https://github.com/GrottoCenter/grottocenter-api/pull/1163

2023-04-01 07:33 UTC, urien reviewed
Du point de vue interface utilisateur c'est parfait. Pour voir si cela fonctionne il faut que le back soit mis à jour

2023-04-03 22:36 UTC, bsoufflet requested changes

2023-04-03 22:36 UTC, bsoufflet commented on packages/web-app/src/components/appli/Entry/Properties.jsx
> +    `${formatMessage({ id: 'Lat.' })} (N) / ${formatMessage({
Lat et Long ne peuvent pas etre S et W au lieu de N et E en fonction du signe des valeurs ? De plus ne faudrait il pas que N S E W soit traduisible ?

2023-04-04 10:18 UTC, BTHOM commented
Rebonjour Benjamin,Tes deux questions ci-dessous (en gras) illustrent un cas particulier de notre échange précédent ; il s'agit ici de définir un format d'affichage dans le système de référence WGS84.L'idéal est de laisser au visiteur/contributeur le choix entre un affichage classique en valeur algébrique (ce qui signifie que le quadrant de référence est toujours N et E) ou un affichage en valeur absolue (ce qui signifie que le quadrant est à ajuster de façon à ce que les valeurs de coordonnées soient toujours positives).La traduction des lettres "N" "S" "E" "W" (pour North, South, East, West) dans la langue et l'alphabet du visiteur/contributeur n'est pas vraiment nécessaire, car ces notations classiques sont largement connues, y compris pour les non anglophones.A suivreBTHPS : les lignes de code que tu as mentionnées me sont assez largement obscures, même si j'en devine vaguement l'objet ;-)envoyé : 4 avril 2023 à 00:36de : "Benjamin S." ***@***.***>à : GrottoCenter/grottocenter-front ***@***.***>cc : Subscribed ***@***.***>objet : Re: [GrottoCenter/grottocenter-front] Removes entrance country input + Adjusts coordinates formatting (PR ***@***.*** requested changes on this pull request.In packages/web-app/src/components/appli/Entry/Properties.jsx:> @@ -73,7 +73,9 @@ const Properties = () => {
   } = useContext(EntryContext);
   const { formatMessage } = useIntl();
   const makeCoordinatesValue = coordinatesValue =>
-    `${formatMessage({ id: 'Lat.' })} / ${formatMessage({ id: 'Long.' })} =
+    `${formatMessage({ id: 'Lat.' })} (N) / ${formatMessage({
Lat et Long ne peuvent pas etre S et W au lieu de N et E en fonction du signe des valeurs ? De plus ne faudrait il pas que N S E W soit traduisible ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-04-04 22:32 UTC, bsoufflet approved these changes

2023-04-13 07:24 UTC, merged