Allow to download exported collections of the database
GrottoCenter/grottocenter-front pull request #910
Opened 2023-06-01 19:36 UTC by vmarseguerra

Add a card in the dashboard to download the different collections of the lastest DB export
The card is only available for leader user

Make use of the new API from https://github.com/GrottoCenter/grottocenter-api/pull/1195

Also update the API page sentences

![image](https://github.com/GrottoCenter/grottocenter-front/assets/6350275/52dd5073-c43a-46ce-a511-7aaa047ff2d4)

2023-06-06 23:33 UTC, bsoufflet commented
@urien : Ne serait il pas bien de rajouter dans cette card un lien d'information vers une page du wiki expliquant ce que c'est que cet export exactement et potentiellement comment l'utiliser et sous quelles conditions ?

2023-06-06 23:37 UTC, bsoufflet requested changes

2023-06-06 23:37 UTC, bsoufflet commented on packages/web-app/src/components/appli/Api.jsx
> +  const wikiApiLink =
![image](https://github.com/GrottoCenter/grottocenter-front/assets/985903/589a23b4-cea2-4f28-8756-1c12fb8fce6c)
il y a des {0} sur la page de test...

2023-06-07 06:54 UTC, urien commented
> @urien : Ne serait il pas bien de rajouter dans cette card un lien d'information vers une page du wiki expliquant ce que c'est que cet export exactement et potentiellement comment l'utiliser et sous quelles conditions ?

On pourrait mettre un message du type
"Consultez les mentions légales pour savoir comment utiliser ces données avec un lien vers"
https://wiki.grottocenter.org/wiki/GrottoCenter:Fr/Legal_and_Privacy_Statement
ou
https://wiki.grottocenter.org/wiki/GrottoCenter:En/Legal_and_Privacy_Statement
pour la version en Anglais

Il faudra qu'on les reprenne / complète pour répondre aux points que tu évoques

2023-06-07 07:33 UTC, vmarseguerra commented on packages/web-app/src/components/appli/Api.jsx
> +  const wikiApiLink =
C'est parce qu'il n'y a pas encore les traductions dans toutes les langues. En anglais la page s'affiche bien.

2023-06-08 16:24 UTC, urien commented on packages/web-app/src/components/appli/Api.jsx
> +  const wikiApiLink =
On a que le Français et l'Anglais qui sont entièrement traduits rapidement. pour les autres langues on a des contributeurs que l'on sollicite de temps en temps et des contributeurs qui ont fait le travail il y a quelques années et dont on a perdu le contact. Il me semble qu'on affiche le texte en Anglais quand la version dans la langue souhaitée n'existe pas

2023-06-08 23:19 UTC, bsoufflet approved these changes

2023-06-12 15:34 UTC, urien reviewed
C'est parfait comme solution. Merci

2023-06-19 22:28 UTC, merged